export const AA_SLOGANS = [
  "One day at a time.",
  "Easy does it.",
  "First things first.",
  "Live and let live.",
  "Let go and let God.",
  "Keep it simple.",
  "This too shall pass.",
  "Keep coming back.",
  "It works if you work it.",
  "Meeting makers make it.",
  "Think, think, think.",
  "But for the grace of God.",
  "How important is it?",
  "Fake it till you make it.",
  "Progress, not perfection.",
  "Keep an open mind.",
  "Utilize, don't analyze.",
  "You are not alone.",
  "Keep the plug in the jug.",
  "90 meetings in 90 days.",
  "Stick with the winners.",
  "Turn it over.",
  "H.A.L.T. — Hungry, Angry, Lonely, Tired.",
  "Do the next right thing.",
  "Act as if.",
  "Stay in the solution, not the problem.",
  "We are only as sick as our secrets.",
  "Expectations are premeditated resentments.",
  "You can't think your way into right acting — you act your way into right thinking.",
  "Recovery is a journey, not a destination.",
  "Sober and serene, or drunk and miserable.",
  "Principles before personalities.",
  "Carry the message, not the mess.",
  "God doesn't make junk.",
  "More will be revealed.",
  "Don't quit before the miracle happens.",
  "Willingness is the key.",
  "Acceptance is the answer.",
  "Gratitude is an attitude.",
  "When all else fails, follow directions.",
  "Get out of the driver's seat.",
  "We didn't cause it, can't control it, can't cure it.",
  "To thine own self be true.",
  "Honesty, open-mindedness, willingness.",
  "Fear is the darkroom where negatives are developed.",
  "Pain is the touchstone of spiritual growth.",
  "Courage to change the things I can.",
  "Grant me serenity to accept the things I cannot change.",
  "Service keeps us sober.",
  "We give it away to keep it.",
];
