export const AA_SLOGANS = [
  { slogan: "One Day at a Time", meaning: "Focus on the present moment rather than worrying about the future; maintain sobriety by taking life step by step." },
  { slogan: "Easy Does It", meaning: "Encourage patience and moderation; avoid rushing or forcing outcomes, especially during stressful situations." },
  { slogan: "Let Go and Let God", meaning: "Release control over things beyond your power and trust a higher power to guide recovery." },
  { slogan: "First Things First", meaning: "Prioritize sobriety above all else; handle other responsibilities after securing your recovery." },
  { slogan: "Keep It Simple", meaning: "Avoid overcomplicating recovery; focus on basic, consistent actions like attending meetings, calling a sponsor, and practicing honesty." },
  { slogan: "Progress, Not Perfection", meaning: "Recovery is about growth and learning, not flawless performance." },
  { slogan: "This Too Shall Pass", meaning: "Remind yourself that difficult emotions and cravings are temporary." },
  { slogan: "Let It Begin with Me", meaning: "Take personal responsibility for your actions and recovery." },
  { slogan: "Think, Think, Think", meaning: "Pause and reflect before acting, especially in triggering situations." },
  { slogan: "Act As If", meaning: "Behave as if you are already the person you want to become, reinforcing positive habits." },
  { slogan: "Live and Let Live", meaning: "Accept others as they are without trying to control or change them; focus on your own recovery." },
  { slogan: "Keep Coming Back", meaning: "Stay engaged with the program even when it's hard — consistency is the foundation of lasting recovery." },
  { slogan: "It Works If You Work It", meaning: "The program delivers results only when you actively apply its principles every day." },
  { slogan: "Meeting Makers Make It", meaning: "Regular attendance at meetings is one of the most reliable tools for long-term sobriety." },
  { slogan: "But for the Grace of God", meaning: "Humility reminder that recovery is a gift — not something earned through willpower alone." },
  { slogan: "How Important Is It?", meaning: "Before reacting to a situation, ask whether it truly matters enough to risk your peace or sobriety." },
  { slogan: "Fake It Till You Make It", meaning: "Act with faith and commitment even before you feel it — the feelings will follow the actions." },
  { slogan: "Keep an Open Mind", meaning: "Willingness to hear new ideas and consider different perspectives is essential to growth in recovery." },
  { slogan: "You Are Not Alone", meaning: "The fellowship exists so no one has to face addiction or recovery in isolation." },
  { slogan: "H.A.L.T.", meaning: "Check in with yourself: are you Hungry, Angry, Lonely, or Tired? These states make relapse more likely." },
  { slogan: "Do the Next Right Thing", meaning: "When overwhelmed, narrow your focus to just the one right action in front of you right now." },
  { slogan: "Stay in the Solution", meaning: "Instead of dwelling on problems, direct your energy toward answers, action, and growth." },
  { slogan: "We Are Only As Sick As Our Secrets", meaning: "Shame and hidden truths keep us trapped; honesty and openness are the path to freedom." },
  { slogan: "Expectations Are Premeditated Resentments", meaning: "Unmet expectations breed anger; releasing expectations opens us to how things actually are." },
  { slogan: "More Will Be Revealed", meaning: "Be patient — understanding and clarity come in their own time as you work the program." },
  { slogan: "Don't Quit Before the Miracle Happens", meaning: "Stay the course even when progress feels invisible; transformation takes time." },
  { slogan: "Willingness Is the Key", meaning: "All recovery requires is the willingness to try — the rest follows from that single opening." },
  { slogan: "Acceptance Is the Answer", meaning: "Resisting reality creates suffering; accepting life on life's terms brings peace." },
  { slogan: "Gratitude Is an Attitude", meaning: "A daily practice of gratitude reshapes perspective and is one of the strongest shields against relapse." },
  { slogan: "Principles Before Personalities", meaning: "Let the values of the program guide decisions rather than personal likes, dislikes, or conflicts." },
  { slogan: "Carry the Message, Not the Mess", meaning: "Share your experience, strength, and hope — not just your struggles and complaints." },
  { slogan: "To Thine Own Self Be True", meaning: "Honest self-knowledge and integrity with yourself are the bedrock of lasting sobriety." },
  { slogan: "Fear Is the Darkroom Where Negatives Are Developed", meaning: "Left unexamined, fear grows and distorts our view of reality; bringing it to light dissolves its power." },
  { slogan: "Pain Is the Touchstone of Spiritual Growth", meaning: "Difficult experiences, when faced with honesty and faith, become the foundation of real wisdom." },
  { slogan: "Service Keeps Us Sober", meaning: "Getting outside ourselves to help others is one of the most powerful tools against self-obsession and craving." },
  { slogan: "We Give It Away to Keep It", meaning: "Sharing the gift of recovery with others is what keeps it alive in ourselves." },
];
