export const TOPICS = [
  {
    id: 'big-book',
    label: 'BIG BOOK',
    icon: 'BookOpen',
    color: '#1a3a5c',
    glowColor: '#2d6a9f',
    shadowColor: 'rgba(26, 58, 92, 0.5)',
    accentColor: '#3d9ecf',
    buttonColor: '#2ba4b5',
    cardTitle: 'Big Book',
    cardSubtitle: 'Alcoholics Anonymous — Chapter 5: How It Works',
    summary: 'Rarely have we seen a person fail who has thoroughly followed our path. Those who do not recover are people who cannot or will not completely give themselves to this simple program. They are naturally incapable of grasping and developing a manner of living which demands rigorous honesty.',
    keyPoints: [
      'Honesty is the foundation of all recovery',
      'Half measures availed us nothing — we stood at the turning point',
      'We asked His protection and care with complete abandon',
      'The steps are suggested as a program of recovery',
      'Our stories disclose in a general way what we used to be like, what happened, and what we are like now',
      'There is One who has all power — that One is God. May you find Him now.',
    ],
    quote: '"Remember that we deal with alcohol — cunning, baffling, powerful! Without help it is too much for us."',
    tags: ['Literature', 'Open Discussion', 'Experience', 'Chapter 5'],
    readings: [
      'Big Book Ch. 5 — "How It Works" (pp. 58–71)',
      'Big Book Ch. 3 — "More About Alcoholism"',
      'Big Book "The Doctor\'s Opinion" (pp. xxiii–xxx)',
    ],
    actionItems: [
      'Read one chapter of the Big Book this week',
      'Share your favorite passage with a newcomer',
      'Write down three ways the program has worked for you',
    ],
    discussionQuestions: [
      'What does "complete abandon" mean in your recovery today?',
      'Which of the four absolutes — honesty, purity, unselfishness, love — is hardest for you?',
      'How has the Big Book changed since your last reading?',
      'What passage first spoke to you when you came in?',
      'How do you carry the message in your daily life?',
    ],
  },
  {
    id: 'reflections',
    label: 'REFLECTIONS',
    icon: 'Sunrise',
    color: '#2a5a3a',
    glowColor: '#4a8a5a',
    shadowColor: 'rgba(42, 90, 58, 0.5)',
    accentColor: '#5ab56a',
    buttonColor: '#48a058',
    cardTitle: 'Daily Reflections',
    cardSubtitle: 'Meditation for Today — Acceptance',
    summary: 'Acceptance is the answer to all my problems today. When I am disturbed, it is because I find some person, place, thing, or situation unacceptable to me, and I can find no serenity until I accept that person, place, thing, or situation as being exactly the way it is supposed to be at this moment. Nothing, absolutely nothing, happens in God\'s world by mistake.',
    keyPoints: [
      'Nothing happens in God\'s world by mistake',
      'Acceptance does not mean approval — it means acknowledging reality',
      'Serenity comes from within, not from changing others',
      'Each day offers a new opportunity for spiritual growth',
      'Meditation and prayer are the channels of a deeper relationship with our Higher Power',
      'We can choose peace over being right',
    ],
    quote: '"And acceptance is the answer to all my problems today." — Big Book, p. 417',
    tags: ['Meditation', 'Reflection', 'Sharing', 'Daily Practice'],
    readings: [
      'Daily Reflections — today\'s entry',
      'Big Book p. 417 — "Acceptance"',
      '12 & 12, Step 11 — Prayer and Meditation',
    ],
    actionItems: [
      'Start each morning with 5 minutes of quiet reflection',
      'Write one thing you need to accept today',
      'Practice the pause before reacting to a difficult person',
    ],
    discussionQuestions: [
      'What are you having trouble accepting right now?',
      'How has acceptance changed a difficult situation for you?',
      'What daily practice helps you find serenity?',
      'When was the last time letting go brought you peace?',
      'How do you distinguish between acceptance and giving up?',
    ],
  },
  {
    id: 'step-talk',
    label: 'STEP TALK',
    icon: 'MessageCircle',
    color: '#5a3a1a',
    glowColor: '#c08030',
    shadowColor: 'rgba(180, 120, 40, 0.5)',
    accentColor: '#e0a030',
    buttonColor: '#d4901a',
    cardTitle: 'Step Talk',
    cardSubtitle: 'Step 1 — Powerlessness & Unmanageability',
    summary: 'We admitted we were powerless over alcohol — that our lives had become unmanageable. Step One is the foundation upon which all the other steps rest. Without a complete surrender, the rest of recovery cannot begin. This admission is not a sign of weakness but rather the first courageous act of a new way of life.',
    keyPoints: [
      'Admitting powerlessness is not weakness — it is the beginning of strength',
      'Unmanageability shows up in every area of life, not just drinking',
      'Denial must be broken before recovery can start',
      'Surrender opens the door to a new way of living',
      'The First Step is something we practice daily, not just once',
      'Powerlessness over people, places, and things extends beyond alcohol',
    ],
    quote: '"We perceive that only through utter defeat are we able to take our first steps toward liberation and strength." — 12 & 12',
    tags: ['Step Study', 'Recovery Practice', 'Group Discussion', 'Step 1'],
    readings: [
      '12 & 12, Step 1 (pp. 21–24)',
      'Big Book Ch. 1 — "Bill\'s Story"',
      'Living Sober — "Staying Away from the First Drink"',
    ],
    actionItems: [
      'Write out three examples of unmanageability in your life',
      'Talk with your sponsor about where you still try to control things',
      'Share your Step 1 experience at this week\'s meeting',
    ],
    discussionQuestions: [
      'What does powerlessness look like in your daily life today?',
      'How did you first come to admit your life was unmanageable?',
      'What does surrender mean to you in practical terms?',
      'In what new ways have you discovered powerlessness beyond alcohol?',
      'How do you practice Step 1 even after years of sobriety?',
    ],
  },
  {
    id: 'bill-sees-it',
    label: 'BILL SEES IT',
    icon: 'Feather',
    color: '#3a2a5a',
    glowColor: '#6a4a9a',
    shadowColor: 'rgba(58, 42, 90, 0.5)',
    accentColor: '#8a6aba',
    buttonColor: '#7a5aaa',
    cardTitle: 'As Bill Sees It',
    cardSubtitle: 'Humility — The Foundation of Growth',
    summary: 'As long as we placed self-reliance first, a genuine reliance upon a Higher Power was out of the question. That basic ingredient of all humility, a desire to seek and do God\'s will, was missing. For us, humility is the recognition of who and what we really are, followed by a sincere attempt to become what we could be.',
    keyPoints: [
      'Self-reliance can become the greatest obstacle to spiritual growth',
      'Humility is not thinking less of yourself, but thinking of yourself less',
      'True reliance on a Higher Power requires letting go of ego',
      'Bill saw humility as the avenue to all the other virtues',
      'Pain is the touchstone of spiritual progress',
      'We grow through our willingness to face uncomfortable truths about ourselves',
    ],
    quote: '"For us, the process of gaining a new perspective was unbelievably painful. It was only by repeated humiliations that we were forced to learn something about humility." — Bill W.',
    tags: ['Bill W. Wisdom', 'Reading & Discussion', 'Spiritual Growth', 'Leadership'],
    readings: [
      'As Bill Sees It — p. 106, "Humility"',
      'As Bill Sees It — p. 95, "Willingness"',
      '12 & 12, Step 7 — "Humbly asked Him"',
    ],
    actionItems: [
      'Identify one area where ego is blocking your growth',
      'Ask someone you trust for honest feedback about a character defect',
      'Practice doing a good deed anonymously this week',
    ],
    discussionQuestions: [
      'Where does self-reliance help vs. hurt your recovery?',
      'Can you share a time when humility opened a door for you?',
      'How do you practice seeking a Higher Power\'s will today?',
      'What is the difference between humility and humiliation?',
      'How has Bill W.\'s writing shaped your understanding of the program?',
    ],
  },
  {
    id: 'bb-vocab',
    label: 'BB VOCAB',
    icon: 'AAIcon',
    color: '#1a4a4a',
    glowColor: '#2a8a8a',
    shadowColor: 'rgba(26, 74, 74, 0.5)',
    accentColor: '#3ababa',
    buttonColor: '#2a9a9a',
    cardTitle: 'Big Book Vocabulary',
    cardSubtitle: 'Key Terms — Understanding the Language of Recovery',
    summary: 'The Big Book uses specific language that carries deep meaning in recovery. Understanding these terms helps us grasp the program more fully and communicate our experience with clarity and purpose.',
    keyPoints: [
      'The Big Book has its own vocabulary rooted in 1930s language',
      'Many terms have specific recovery meanings beyond everyday usage',
      'Understanding the language deepens our comprehension of the program',
      'Sharing definitions helps newcomers feel included and informed',
      'Bill and the early members chose their words with great care',
      'The language of the heart transcends dictionary definitions',
    ],
    quote: '"We are sure God wants us to be happy, joyous, and free." — Big Book, p. 133',
    tags: ['Vocabulary', 'Education', 'Big Book', 'Newcomer-Friendly'],
    readings: [
      'Big Book — Appendices (Spiritual Experience, The Medical View)',
      'Big Book — The Doctor\'s Opinion',
      'Living Sober — Glossary and Key Concepts',
    ],
    actionItems: [
      'Look up one unfamiliar Big Book term this week',
      'Share a definition with a newcomer at your next meeting',
      'Start a personal glossary of recovery terms',
    ],
    discussionQuestions: [
      'Which Big Book term confused you when you first came in?',
      'How has understanding the language changed your recovery?',
      'What term do you think newcomers struggle with most?',
      'How do you explain AA concepts to someone outside the program?',
      'Which Big Book phrase has the deepest personal meaning for you?',
    ],
  },
  {
    id: 'random',
    label: 'RANDOM',
    icon: 'Shuffle',
    color: '#4a4a52',
    glowColor: '#7a7a85',
    shadowColor: 'rgba(74, 74, 82, 0.5)',
    accentColor: '#9a9aa5',
    buttonColor: '#2ba4b5',
    cardTitle: 'Random Topic',
    cardSubtitle: 'All Categories — Gratitude in Recovery',
    summary: 'Gratitude is the heart of recovery. When we shift from focusing on what we have lost to what we have been given, our entire outlook changes. An attitude of gratitude turns what we have into enough. It is the great multiplier — the more we practice it, the more we receive.',
    keyPoints: [
      'Gratitude lists are a powerful tool against self-pity',
      'Thankfulness for sobriety — one day at a time — is the foundation',
      'Helping others is the greatest expression of gratitude',
      'Even our hardships become gifts when viewed through recovery',
      'A grateful heart has no room for resentment',
      'Gratitude transforms our perspective from scarcity to abundance',
    ],
    quote: '"No matter how far down the scale we have gone, we will see how our experience can benefit others." — Big Book, p. 84',
    tags: ['Open Format', 'Any Category', 'All Welcome', 'Gratitude'],
    readings: [
      'Big Book p. 84 — "The Promises"',
      'Daily Reflections — "Gratitude" entries',
      'Living Sober — "Being Grateful"',
    ],
    actionItems: [
      'Write a gratitude list of 10 things before bed tonight',
      'Thank someone in the program who made a difference in your life',
      'Share a gratitude moment at your next meeting',
    ],
    discussionQuestions: [
      'What are three things you are grateful for in your recovery today?',
      'How has gratitude changed the way you handle difficulties?',
      'Who in the program are you most grateful for, and why?',
      'What unexpected gift has recovery brought you?',
      'How do you stay grateful when life gets hard?',
    ],
  },
];
