export const TOPICS = [
  {
    id: 'big-book',
    label: 'RECOVERY READING',
    icon: 'BookOpen',
    color: '#1a3a5c',
    glowColor: '#2d6a9f',
    shadowColor: 'rgba(26, 58, 92, 0.5)',
    accentColor: '#3d9ecf',
    buttonColor: '#2ba4b5',
    cardTitle: 'Recovery Reading',
    cardSubtitle: 'Foundations of a Sober Life',
    summary: 'Recovery literature gives us a shared language and a roadmap. Reading and discussing the principles of sobriety together helps us see ourselves in each other\'s stories, find hope in shared experience, and deepen our understanding of what it means to live free from addiction.',
    keyPoints: [
      'Honesty is the foundation of all lasting recovery',
      'Half measures in working a program leave us vulnerable',
      'Surrender is not defeat — it is the beginning of real freedom',
      'The steps are a suggested path, not a set of rules',
      'Our stories connect us — what we were, what changed, who we are now',
      'A power greater than ourselves can restore what addiction took',
    ],
    quote: '"Sharing our experience, strength, and hope with one another is what keeps recovery alive."',
    tags: ['Literature', 'Open Discussion', 'Experience', 'Foundations'],
    readings: [
      'Any recovery literature that has shaped your sobriety',
      'Personal stories of what it was like, what happened, and what it\'s like now',
      'Principles of honesty, willingness, and open-mindedness in recovery',
    ],
    actionItems: [
      'Read something recovery-related this week and bring a passage to discuss',
      'Share your favorite recovery concept with a newcomer',
      'Write down three ways working a program has changed your life',
    ],
    discussionQuestions: [
      'What recovery reading has had the biggest impact on you?',
      'Which recovery principle do you find hardest to practice daily?',
      'How has your understanding of powerlessness evolved over time?',
      'What passage or idea first gave you hope when you came in?',
      'How do you carry the message of recovery in your daily life?',
    ],
  },
  {
    id: 'reflections',
    label: 'REFLECTIONS',
    icon: 'Sunrise',
    color: '#2a5a3a',
    glowColor: '#4a8a5a',
    shadowColor: 'rgba(42, 90, 58, 0.5)',
    accentColor: '#5ab56a',
    buttonColor: '#48a058',
    cardTitle: 'Reflections',
    cardSubtitle: 'Meditation for Today — Acceptance',
    summary: 'Acceptance is one of the most powerful tools in recovery. When we stop fighting reality and start meeting life as it is, we find a peace that no circumstance can take away. Serenity does not come from getting what we want — it comes from releasing our grip on what we cannot control.',
    keyPoints: [
      'Acceptance does not mean approval — it means acknowledging reality as it is',
      'Serenity comes from within, not from changing people or circumstances',
      'Each day offers a new opportunity for spiritual and personal growth',
      'Quiet reflection — even five minutes — can transform how we move through the day',
      'Meditation connects us to something deeper than our daily worries',
      'We can choose peace over the need to be right',
    ],
    quote: '"Serenity is not freedom from the storm — it is peace within the storm."',
    tags: ['Meditation', 'Reflection', 'Sharing', 'Daily Practice'],
    readings: [
      'Any daily meditation book that supports your recovery',
      'Your own journal — what acceptance has looked like this week',
      'The Serenity Prayer and how it applies to something in your life today',
    ],
    actionItems: [
      'Start each morning with 5 minutes of quiet reflection before reaching for your phone',
      'Write down one thing you are struggling to accept and sit with it today',
      'Practice the pause before reacting to a difficult person or situation',
    ],
    discussionQuestions: [
      'What are you having trouble accepting right now?',
      'How has acceptance changed a difficult situation in your life?',
      'What daily practice helps you find and maintain serenity?',
      'When was the last time letting go of control brought you peace?',
      'How do you distinguish between acceptance and giving up?',
    ],
  },
  {
    id: 'step-talk',
    label: 'STEP TALK',
    icon: 'MessageCircle',
    color: '#5a3a1a',
    glowColor: '#c08030',
    shadowColor: 'rgba(180, 120, 40, 0.5)',
    accentColor: '#e0a030',
    buttonColor: '#d4901a',
    cardTitle: 'Step Talk',
    cardSubtitle: 'Step 1 — Powerlessness & Unmanageability',
    summary: 'Admitting powerlessness is not the end — it is the beginning of a new way of life. The first step toward freedom is recognizing that our own willpower alone was never going to be enough. Surrender is the courageous act that opens every door recovery has to offer.',
    keyPoints: [
      'Admitting powerlessness is not weakness — it is the beginning of real strength',
      'Unmanageability shows up in every area of life, not just in our drinking',
      'Denial must be broken before genuine recovery can start',
      'Surrender opens the door to a way of living we could not find alone',
      'Step work is not a one-time event — it is a daily practice',
      'Powerlessness over people, places, and things extends beyond addiction',
    ],
    quote: '"Until we could admit the problem completely, we could not begin to find the solution."',
    tags: ['Step Study', 'Recovery Practice', 'Group Discussion', 'Step 1'],
    readings: [
      'Step 1 in any twelve-step workbook or guide',
      'Personal stories about coming to terms with powerlessness',
      'Reflections on what unmanageability looked like before recovery',
    ],
    actionItems: [
      'Write out three concrete examples of unmanageability in your life before recovery',
      'Talk with your sponsor about where you still try to control outcomes today',
      'Share your Step 1 experience at a meeting this week',
    ],
    discussionQuestions: [
      'What does powerlessness look like in your daily life today?',
      'How did you first come to admit your life had become unmanageable?',
      'What does surrender mean to you in practical terms?',
      'In what areas beyond addiction have you discovered powerlessness?',
      'How do you practice the first step even after years of sobriety?',
    ],
  },
  {
    id: 'bill-sees-it',
    label: 'WISDOM',
    icon: 'Feather',
    color: '#3a2a5a',
    glowColor: '#6a4a9a',
    shadowColor: 'rgba(58, 42, 90, 0.5)',
    accentColor: '#8a6aba',
    buttonColor: '#7a5aaa',
    cardTitle: 'Wisdom',
    cardSubtitle: 'Humility — The Foundation of Growth',
    summary: 'As long as we place self-reliance first, genuine reliance on anything greater than ourselves is impossible. Humility is not about thinking less of ourselves — it is about seeing ourselves clearly, with honesty and compassion. It is the foundation on which all other spiritual growth is built.',
    keyPoints: [
      'Self-reliance can become the greatest obstacle to spiritual growth',
      'Humility means seeing yourself honestly — not harshly, not proudly',
      'True freedom requires letting go of the need to be right or in control',
      'Pain honestly faced becomes the foundation of real wisdom',
      'We grow through our willingness to face uncomfortable truths about ourselves',
      'The willingness to change is itself a form of courage',
    ],
    quote: '"Growth begins at the edge of our comfort zone — not in the places we already feel safe."',
    tags: ['Wisdom', 'Reading & Discussion', 'Spiritual Growth', 'Character'],
    readings: [
      'Any recovery passage about humility, ego, and spiritual growth',
      'Personal reflections on where self-will has caused problems',
      'Stories of transformation through willingness and honest self-appraisal',
    ],
    actionItems: [
      'Identify one area where ego or self-will is blocking your growth right now',
      'Ask someone you trust for honest, caring feedback on a character defect',
      'Do one anonymous act of service or kindness this week',
    ],
    discussionQuestions: [
      'Where does self-reliance help your recovery, and where does it hurt it?',
      'Can you share a time when humility opened an unexpected door for you?',
      'How do you practice seeking guidance from something greater than yourself?',
      'What is the difference between humility and humiliation to you?',
      'What piece of recovery wisdom has shaped you the most?',
    ],
  },
  {
    id: 'bb-vocab',
    label: 'RECOVERY VOCAB',
    icon: 'AAIcon',
    color: '#1a4a4a',
    glowColor: '#2a8a8a',
    shadowColor: 'rgba(26, 74, 74, 0.5)',
    accentColor: '#3ababa',
    buttonColor: '#2a9a9a',
    cardTitle: 'Recovery Vocabulary',
    cardSubtitle: 'Key Terms — Understanding the Language of Recovery',
    summary: 'Recovery has its own language — words and phrases that carry specific meaning for those who have walked this path. Understanding these terms helps us communicate our experience clearly, connect with others in the fellowship, and grasp the principles of sobriety at a deeper level.',
    keyPoints: [
      'Recovery has a vocabulary rooted in shared experience and spiritual principles',
      'Many terms carry meanings that go deeper than their everyday dictionary definitions',
      'Understanding the language helps newcomers feel included and find their footing',
      'Sharing definitions opens discussion and deepens everyone\'s understanding',
      'The language of the heart often matters more than precise definitions',
      'Words like surrender, acceptance, and service take on new meaning in recovery',
    ],
    quote: '"When we find the words for our experience, we begin to understand it — and to share it with others."',
    tags: ['Vocabulary', 'Education', 'Recovery Language', 'Newcomer-Friendly'],
    readings: [
      'Any recovery glossary or introductory guide to the twelve-step process',
      'Personal reflections on terms that confused or surprised you early in recovery',
      'Discussion of how recovery terms like "powerless," "amends," and "inventory" apply today',
    ],
    actionItems: [
      'Pick one recovery term this week and journal about what it means to you personally',
      'Share a definition or concept with a newcomer in your group',
      'Start a personal recovery glossary — add one word each week',
    ],
    discussionQuestions: [
      'Which recovery term confused you the most when you first came in?',
      'How has your understanding of a word like "surrender" or "acceptance" changed over time?',
      'What term do you think newcomers struggle with most, and why?',
      'How do you explain recovery concepts to people outside the program?',
      'Which recovery phrase has the deepest personal meaning for you today?',
    ],
  },
  {
    id: 'twelve-twelve',
    label: '12 & 12',
    icon: 'BookMarked',
    color: '#1a3a2a',
    glowColor: '#2a7a5a',
    shadowColor: 'rgba(26, 58, 42, 0.5)',
    accentColor: '#3abf8a',
    buttonColor: '#2aaf7a',
    cardTitle: '12 & 12',
    cardSubtitle: 'The Twelve Steps & Twelve Traditions',
    summary: 'The Twelve Steps and Twelve Traditions offer a deeper look at how the steps work in daily life and how the traditions keep our groups healthy and unified. Each principle explored here is a practical guide for living — one day at a time.',
    keyPoints: [
      'The steps offer a way out of self-centered fear and into spiritual freedom',
      'The traditions protect the group so it can protect the individual',
      'Each step builds on the one before it — no step stands alone',
      'Spiritual progress, not perfection, is the goal',
      'Unity, service, and recovery are the three legacies of the program',
      'The traditions work because they put principles before personalities',
    ],
    quote: '"None of us is as wise as all of us — the traditions remind us to trust the group conscience."',
    tags: ['12 & 12', 'Steps', 'Traditions', 'Group Discussion'],
    readings: [
      'Any step or tradition from your own twelve-step study',
      'Personal reflections on how a tradition protects your home group',
      'A sponsor conversation about how a step applies to your life today',
    ],
    actionItems: [
      'Read one step or tradition this week and write a reflection on it',
      'Bring a tradition topic to your home group business meeting',
      'Share how a step principle showed up in a situation this week',
    ],
    discussionQuestions: [
      'Which step or tradition has had the biggest impact on you and why?',
      'How do the traditions protect the unity of your home group?',
      'What step principle are you currently working to practice daily?',
      'How has your understanding of the steps deepened over time?',
      'Which tradition do you think is most misunderstood, and why?',
    ],
  },
  {
    id: 'slogans',
    label: 'SLOGANS',
    icon: 'Sparkles',
    color: '#3a3010',
    glowColor: '#c8a020',
    shadowColor: 'rgba(180, 140, 10, 0.5)',
    accentColor: '#d4b020',
    buttonColor: '#b89018',
    cardTitle: 'Recovery Slogans',
    cardSubtitle: 'Wisdom Distilled — The Sayings That Keep Us Sober',
    summary: 'Recovery slogans are bite-sized wisdom passed down through generations of the fellowship. Simple enough to remember in a crisis, deep enough to sustain a lifetime of growth — these phrases have kept more people sober than most realize.',
    keyPoints: [
      'Slogans are tools — use them when thinking gets too complicated',
      'Keep It Simple means stop overthinking and do the next right thing',
      'One Day at a Time makes the impossible manageable',
      'Easy Does It is a reminder that urgency and panic rarely improve outcomes',
      'Let Go and Let God acknowledges the limits of our own power',
      'This Too Shall Pass reminds us that no feeling — good or bad — is permanent',
    ],
    quote: '"The slogans of recovery are the wisdom of thousands distilled into words that fit on a bumper sticker — and saved a life."',
    tags: ['Slogans', 'Wisdom', 'Fellowship', 'Daily Practice'],
    readings: [
      'Any slogan that has been meaningful to your recovery this week',
      'Personal story of a time a slogan helped you through a difficult moment',
      'Reflection on how a simple phrase changed your thinking in a crisis',
    ],
    actionItems: [
      'Pick one slogan and apply it deliberately to a situation this week',
      'Share a slogan with a newcomer and explain what it means to you personally',
      'Write about a time a slogan stopped a relapse or a bad decision',
    ],
    discussionQuestions: [
      'Which recovery slogan has meant the most to you, and why?',
      'Can you share a time a slogan helped you through a difficult moment?',
      'Which slogan do you find hardest to practice, and what gets in the way?',
      'How do you explain recovery slogans to people outside the program?',
      'What slogan would you put on your own recovery "bumper sticker" today?',
    ],
  },
  {
    id: 'random',
    label: 'RANDOM',
    icon: 'Shuffle',
    color: '#4a4a52',
    glowColor: '#7a7a85',
    shadowColor: 'rgba(74, 74, 82, 0.5)',
    accentColor: '#9a9aa5',
    buttonColor: '#2ba4b5',
    cardTitle: 'Random Topic',
    cardSubtitle: 'All Categories — Gratitude in Recovery',
    summary: 'Gratitude is the heart of recovery. When we shift our focus from what we have lost to what we have been given, our entire outlook changes. An attitude of gratitude transforms what we have into enough. The more we practice it, the more we find to be grateful for.',
    keyPoints: [
      'A daily gratitude practice is one of the most powerful tools against self-pity',
      'Thankfulness for sobriety — one day at a time — anchors everything else',
      'Helping others is one of the deepest expressions of gratitude in action',
      'Even our hardships can become gifts when viewed through the lens of recovery',
      'A grateful heart leaves little room for resentment or fear',
      'Gratitude transforms our perspective from scarcity to abundance',
    ],
    quote: '"Gratitude turns what we have into enough — and more than enough."',
    tags: ['Open Format', 'Any Category', 'All Welcome', 'Gratitude'],
    readings: [
      'Any recovery passage about gratitude, service, or the gifts of sobriety',
      'The Promises of recovery — what a sober life can look like',
      'Personal stories of unexpected gifts that came through working a program',
    ],
    actionItems: [
      'Write a gratitude list of 10 things before bed tonight',
      'Thank someone in the program who made a real difference in your recovery',
      'Share a moment of genuine gratitude at your next meeting',
    ],
    discussionQuestions: [
      'What are three things you are grateful for in your recovery today?',
      'How has practicing gratitude changed the way you handle difficulty?',
      'Who in your recovery community are you most grateful for, and why?',
      'What unexpected gift has sobriety brought into your life?',
      'How do you stay grateful when life gets genuinely hard?',
    ],
  },
];
