// Generates card variants for each topic. Each topic has 50+ unique cards.
// Cards are built from template arrays and combined programmatically.
// All content is original. This app is not affiliated with AA World Services, Inc.

const BB_CARDS = [
  { sub: 'Chapter 1 — A Founder\'s Story', sum: 'The co-founder of modern twelve-step recovery shares his journey from hopeless addiction to a life of purpose, illustrating the progression of the disease and the spiritual change that made recovery possible.', q: '"The most important thing is not where we came from, but where we are going — and that we do not have to go there alone."', tags: ['Chapter 1', 'Founders'] },
  { sub: 'Chapter 2 — There Is a Solution', sum: 'The solution lies in a spiritual experience. This chapter explains what addiction really is and why only a profound change in consciousness can relieve it.', q: '"The turning point comes when we stop trying to manage the problem and start allowing something greater to manage us."', tags: ['Chapter 2', 'Solution'] },
  { sub: 'Chapter 3 — The Mental Obsession', sum: 'This discussion demolishes the idea that a true addict can ever drink normally again. It presents compelling examples of the mental obsession that precedes every relapse.', q: '"The belief that we can someday drink like normal people is the single most dangerous lie addiction tells us."', tags: ['Chapter 3', 'Obsession'] },
  { sub: 'Chapter 4 — For the Skeptic', sum: 'This chapter speaks to those who struggle with the concept of God, suggesting an open mind and willingness to believe in a power greater than ourselves is all that is required.', q: '"All that is required to begin is the willingness to believe that something greater than our own thinking might help."', tags: ['Chapter 4', 'Higher Power'] },
  { sub: 'Chapter 5 — How It Works', sum: 'Those who thoroughly follow the path of recovery rarely fail. This chapter lays out the twelve steps and emphasizes rigorous honesty as the foundation.', q: '"Addiction is cunning, baffling, and powerful — but the program, honestly worked, is more powerful still."', tags: ['Chapter 5', 'Steps'] },
  { sub: 'Chapter 6 — Into Action', sum: 'Steps 5 through 9 in practical detail. Action, not just understanding, produces results. A faith that is not lived is not a faith at all.', q: '"Understanding the steps is not enough — we have to take them, and keep taking them, one day at a time."', tags: ['Chapter 6', 'Action'] },
  { sub: 'Chapter 7 — Working With Others', sum: 'Nothing ensures immunity from drinking like intensive work with other addicts. This chapter teaches how to carry the message of recovery effectively.', q: '"Our own recovery depends on helping others find theirs — this is not charity, it is necessity."', tags: ['Chapter 7', 'Service'] },
  { sub: 'Chapter 8 — The Family and Recovery', sum: 'Acknowledges the suffering addiction inflicts on loved ones and offers guidance for patience, understanding, and family recovery together.', q: '"Recovery changes not just the person who was suffering, but everyone around them — if they let it."', tags: ['Chapter 8', 'Family'] },
  { sub: 'Chapter 9 — The Family Afterward', sum: 'Recovery brings changes the whole family must adjust to. Rebuilding trust and family life requires patience and humility from everyone involved.', q: '"Those of us who have found our way out of addiction owe something to those still looking for the door."', tags: ['Chapter 9', 'Family'] },
  { sub: 'Chapter 10 — To Employers', sum: 'Addiction is a disease, not a moral failing. A person in solid recovery may become an organization\'s most committed and reliable contributor.', q: '"Someone who has faced the depths of addiction and come back has a strength most people never have to develop."', tags: ['Chapter 10', 'Work'] },
  { sub: 'Chapter 11 — A Vision for You', sum: 'A hopeful picture of what life can be like in recovery and the community of healing that awaits anyone willing to reach for it.', q: '"The life that waits on the other side of surrender is more than most of us ever dared to imagine."', tags: ['Chapter 11', 'Hope'] },
  { sub: 'The Medical Perspective', sum: 'Addiction involves both a physical component and a mental obsession. A profound inner change is necessary for lasting recovery.', q: '"We could not simply think our way into recovery. The change had to happen at a deeper level than thought."', tags: ['Medical', 'Disease'] },
  { sub: 'The Promises of Recovery', sum: 'Working the first nine steps brings tangible gifts: new freedom, new happiness, peace, and the ability to help others who are still suffering.', q: '"Recovery gives back far more than addiction ever took — but we have to do the work to receive those gifts."', tags: ['Promises', 'Hope'] },
  { sub: 'Acceptance as a Daily Practice', sum: 'Acceptance is the answer to so many of life\'s problems. When we stop fighting reality, serenity becomes possible in any circumstance.', q: '"We cannot change what we refuse to accept — and we cannot accept what we are still pretending is not real."', tags: ['Acceptance', 'Serenity'] },
  { sub: 'Freedom from Resentment', sum: 'Praying for those we resent sets us free. Learning to release resentment is one of the most transformative practices in recovery.', q: '"Holding onto resentment is choosing to let someone else live rent-free in your head."', tags: ['Resentment', 'Freedom'] },
  { sub: 'Step 3 — Surrender Prayer', sum: 'A surrendering of self-will. This practice marks the turning point from self-reliance to trust in a power greater than ourselves.', q: '"We cannot simultaneously grip control with both hands and ask a Higher Power to guide us. We have to let go first."', tags: ['Step 3', 'Prayer'] },
  { sub: 'Step 7 — Asking for Change', sum: 'Humbly asking a Higher Power to remove our shortcomings so we can better serve others. A practice of surrender and trust.', q: '"We do not ask to become perfect — only to become useful, and to stop causing harm."', tags: ['Step 7', 'Prayer'] },
  { sub: 'Step 4 — The Resentment Inventory', sum: 'Examining resentments is the core of Step 4. Listing who, why, and what our part was brings clarity and eventually freedom.', q: '"Resentment is a primary threat to lasting sobriety — it poisons from within."', tags: ['Step 4', 'Resentment'] },
  { sub: 'Step 4 — The Fear Inventory', sum: 'By identifying and sharing our fears, we begin to trust that something greater than ourselves can handle what we cannot.', q: '"Fear has driven most of our destructive behavior. Naming it is the first step toward releasing it."', tags: ['Step 4', 'Fear'] },
  { sub: 'Daily Reprieve', sum: 'Our sobriety depends on maintaining our spiritual condition each day. We are not permanently cured — we live in a daily state of grace.', q: '"Recovery is not something we achieve and then own. It is something we maintain — one day at a time."', tags: ['Daily Reprieve', 'Maintenance'] },
  { sub: 'Emotional Sobriety', sum: 'Beyond physical sobriety lies emotional sobriety — the ability to handle life\'s ups and downs without being overwhelmed or reaching for a substance.', q: '"Physical sobriety was just the beginning. Emotional sobriety is the ongoing work of becoming a whole person."', tags: ['Emotional Sobriety', 'Growth'] },
  { sub: 'Principles Before Personalities', sum: 'Recovery calls us to place principles above personalities. The message matters more than the person carrying it.', q: '"No individual person is more important than the principles that keep us all well."', tags: ['Principles', 'Anonymity'] },
  { sub: 'Personal Stories — Identification', sum: 'Shared experience is the bedrock of recovery. Every story carries a common thread — hope. The details differ, but the feelings are the same.', q: '"We recover in community by recognizing ourselves in each other\'s stories."', tags: ['Stories', 'Identification'] },
  { sub: 'Relationship Inventory', sum: 'Examining where our behavior has been selfish, dishonest, or harmful in relationships — about honesty, not shame.', q: '"The most important relationship question in recovery is always the same: what was my part?"', tags: ['Step 4', 'Relationships'] },
  { sub: 'Step 4 — Searching Moral Inventory', sum: 'A thorough and honest look at ourselves. Writing reveals patterns of behavior that have caused harm and kept us stuck.', q: '"Writing it down makes it real. We cannot quietly revise our inventory when it becomes uncomfortable."', tags: ['Step 4', 'Inventory'] },
  { sub: 'Steps 8 and 9 — Making Amends', sum: 'We list those we have harmed and become willing to make amends. Direct amends wherever possible, except when doing so would injure others.', q: '"Making amends is not about what we feel — it is about what we owe. Courage gets us started."', tags: ['Steps 8-9', 'Amends'] },
  { sub: 'Step 10 — Continued Inventory', sum: 'The maintenance step. By continuing to take personal inventory and promptly admitting when we are wrong, we keep our side of the street clean.', q: '"We watch for selfishness, dishonesty, resentment, and fear — not because we are failures, but because we are human."', tags: ['Step 10', 'Maintenance'] },
  { sub: 'Step 11 — Prayer and Meditation', sum: 'Deepening conscious contact with a Higher Power through prayer and meditation. The spiritual practice that sustains long-term recovery.', q: '"Prayer is how we talk. Meditation is how we listen. Both are needed."', tags: ['Step 11', 'Meditation'] },
  { sub: 'Step 12 — Carrying the Message', sum: 'Having had a spiritual awakening as a result of these steps, we carry this message to others and practice these principles in all our affairs.', q: '"We protect our own sobriety by helping others find theirs — this is the final gift the steps give us."', tags: ['Step 12', 'Service'] },
  { sub: 'Powerlessness Over People', sum: 'Recovery extends beyond alcohol. We are powerless over people, places, and things. Accepting this brings lasting peace.', q: '"Control is the illusion that fed our addiction. Acceptance is the truth that sets us free."', tags: ['Step 1', 'Powerlessness'] },
];

const REFL_CARDS = [
  { sub: 'New Beginnings', sum: 'Each new day brings opportunity to renew our commitment to recovery, reflect on growth, and set intentions grounded in what we have learned.', q: '"Every morning is a new chance to show up differently than we did yesterday."', tags: ['New Beginnings', 'Gratitude'] },
  { sub: 'Letting Go of Control', sum: 'Our need to control creates suffering. Letting go is trusting that a power greater than ourselves is at work, even when we cannot see it.', q: '"We held on so tightly to how things had to be that we missed how good things could have been."', tags: ['Control', 'Surrender'] },
  { sub: 'Living in the Present', sum: 'Anxiety comes from the future; depression from the past. Recovery teaches us to live in the only moment we truly have — now.', q: '"The past is a memory and the future is a plan. The present is the only place where recovery actually happens."', tags: ['Present Moment', 'Mindfulness'] },
  { sub: 'Dealing with Anger', sum: 'Anger is natural but can threaten sobriety when left unaddressed. Learning to process it without acting out is essential to lasting recovery.', q: '"Anger tells us something true about ourselves — what we do with that information is what matters."', tags: ['Anger', 'Emotions'] },
  { sub: 'Gratitude Practice', sum: 'Gratitude is the antidote to self-pity, resentment, and fear. A daily gratitude practice genuinely transforms our outlook.', q: '"It is impossible to feel grateful and sorry for yourself at the same time. Choose gratitude."', tags: ['Gratitude', 'Practice'] },
  { sub: 'Self-Pity and Its Cure', sum: 'Self-pity isolates us and can lead back to drinking. The cure is action — getting outside ourselves through service and connection.', q: '"Self-pity is a trap that looks like a resting place. The only way out is through."', tags: ['Self-Pity', 'Service'] },
  { sub: 'Acceptance in Practice', sum: 'Learning to distinguish what we can and cannot change is the practical heart of lasting peace in recovery.', q: '"Accepting what we cannot change is not giving up — it is putting our energy where it can actually do some good."', tags: ['Acceptance', 'Serenity'] },
  { sub: 'Loneliness in Recovery', sum: 'Loneliness is common in early recovery, but the fellowship offers a genuine remedy. We are never as alone as we feel.', q: '"Recovery communities are not just groups — they are proof that we were never as alone as addiction told us we were."', tags: ['Loneliness', 'Fellowship'] },
  { sub: 'Expectations vs. Reality', sum: 'Unmet expectations are the seeds of resentment. Releasing expectations opens us to what life actually has to offer.', q: '"Expectations are invitations for disappointment. Openness is the antidote."', tags: ['Expectations', 'Acceptance'] },
  { sub: 'Trusting the Process', sum: 'Recovery is not a straight line. Trusting the process means believing the work pays off even when we cannot yet see how.', q: '"We did not get sick overnight, and we will not get well overnight. Trust the process."', tags: ['Trust', 'Faith'] },
  { sub: 'Patience in Recovery', sum: 'We want results immediately, but genuine growth takes time. Patience with ourselves and others is itself a spiritual practice.', q: '"More will be revealed — and it always is, to those who stay and keep doing the work."', tags: ['Patience', 'Growth'] },
  { sub: 'Honesty with Self', sum: 'Self-deception kept us sick. Honest self-appraisal is the foundation of all spiritual progress in recovery.', q: '"The most important conversation in recovery is the one you have with yourself when no one is watching."', tags: ['Honesty', 'Self-Awareness'] },
  { sub: 'Forgiveness', sum: 'Forgiving others — and ourselves — frees us from the prison of resentment. Forgiveness does not mean condoning the harm.', q: '"Holding onto resentment keeps us chained to the past. Forgiveness is freedom — not for them, but for us."', tags: ['Forgiveness', 'Resentment'] },
  { sub: 'Service as Medicine', sum: 'When we are of service to others, our own problems shrink. Helping someone else is one of the most reliable tools in recovery.', q: '"The fastest way out of our own head is to walk into someone else\'s pain and try to help."', tags: ['Service', 'Action'] },
  { sub: 'Courage to Change', sum: 'Change requires courage — the courage to face our fears, admit our wrongs, and step into the unknown trusting we will be okay.', q: '"Courage is not the absence of fear. It is taking the next step anyway."', tags: ['Courage', 'Change'] },
  { sub: 'Finding Your Higher Power', sum: 'A higher power can be anything genuinely greater than ourselves. The journey to find one is deeply personal and ongoing.', q: '"The only requirement for a Higher Power is that it be more reliable than our own best thinking got us."', tags: ['Higher Power', 'Faith'] },
  { sub: 'Humility vs. Pride', sum: 'Pride keeps us stuck; humility opens doors. True humility is simply seeing ourselves as we really are — no more, no less.', q: '"Pride tells us we are the exception. Humility reminds us we are not — and that is actually a relief."', tags: ['Humility', 'Pride'] },
  { sub: 'Dealing with Loss', sum: 'Loss is part of life. In recovery, we learn to grieve without drinking and find strength in our community and our faith.', q: '"We do not have to drink over grief. Feeling it, sharing it, and moving through it is possible — and it heals."', tags: ['Loss', 'Grief'] },
  { sub: 'Relationships in Recovery', sum: 'Recovery transforms our relationships. We learn to be honest, vulnerable, and present with the people we love.', q: '"Recovery does not just change us — it changes how we show up for everyone around us."', tags: ['Relationships', 'Growth'] },
  { sub: 'Fear of the Future', sum: 'Fear of what might happen robs us of today. Recovery teaches us to trust that we will be given what we need, when we need it.', q: '"Most of what we feared never happened. And everything that did, we survived — often with help."', tags: ['Fear', 'Faith'] },
  { sub: 'The Gift of Desperation', sum: 'Desperation brought many of us to recovery. What felt like our lowest point was actually the beginning of the most important change of our lives.', q: '"Desperation is not the end — it is often the door. We just have to be willing to walk through it."', tags: ['Desperation', 'Hope'] },
  { sub: 'Practicing Kindness', sum: 'Simple acts of kindness connect us to others and remind us that recovery is about far more than just not drinking.', q: '"Kindness costs nothing and changes everything. In recovery, we try to give it freely."', tags: ['Kindness', 'Love'] },
  { sub: 'Spiritual Growth', sum: 'Spiritual growth is not about religion — it is about becoming more honest, open, and willing. It happens gradually and often when we are not looking.', q: '"Spiritual progress is not measured in peak experiences but in the daily choices we make when no one is watching."', tags: ['Spirituality', 'Progress'] },
  { sub: 'Dealing with Criticism', sum: 'Criticism can trigger our defenses. In recovery, we learn to pause, listen, consider the grain of truth, and respond rather than react.', q: '"The person who never hears criticism never grows. Learning to sit with it rather than fight it is a real skill."', tags: ['Criticism', 'Restraint'] },
  { sub: 'Joy in Sobriety', sum: 'Recovery is not just about avoiding pain — it is about discovering genuine joy, laughter, and connection that we thought we had lost forever.', q: '"Joy in sobriety is not the absence of problems. It is the presence of something worth protecting."', tags: ['Joy', 'Happiness'] },
  { sub: 'When Life Gets Hard', sum: 'Difficult times test our recovery but also reveal its depth. The tools of the program work in every situation — if we actually use them.', q: '"Hard times are not proof that recovery is not working. They are proof that we need it."', tags: ['Adversity', 'Resilience'] },
  { sub: 'Surrendering Outcomes', sum: 'We do the footwork and leave the results to a Higher Power. Surrendering outcomes frees us from anxiety and the exhaustion of control.', q: '"We are responsible for the effort. We are not responsible for the result. That is a Higher Power\'s job."', tags: ['Surrender', 'Outcomes'] },
  { sub: 'The Power of Meetings', sum: 'Meetings are where we share, listen, and connect. They remind us we are not alone and keep our recovery alive one share at a time.', q: '"Meetings are where recovery lives. They are not perfect, but they are where we find each other."', tags: ['Meetings', 'Fellowship'] },
  { sub: 'Living Amends', sum: 'Some amends cannot be made in words. Living amends means consistently showing up as a changed person, day after day.', q: '"A living amends cannot be undone. It is the changed life, lived one day at a time."', tags: ['Amends', 'Change'] },
  { sub: 'Recovery Wisdom', sum: 'Recovery distills deep truths into simple practices: do the next right thing, stay in the present, help others, keep it simple.', q: '"The wisdom of recovery is simple — but simple is not the same as easy."', tags: ['Wisdom', 'Simplicity'] },
];

// Step Talk — The 12 Steps of twelve-step recovery
const STEP_CARDS = [
  { sub: 'Step 1 — Powerlessness', sum: 'We admitted we were powerless over alcohol — that our lives had become unmanageable. This honest admission is the foundation upon which all other steps rest.', q: '"Admitting powerlessness is not defeat — it is the first act of genuine courage in recovery."', tags: ['Step 1', 'Powerlessness'] },
  { sub: 'Step 1 — Unmanageability', sum: 'Unmanageability shows up in every area of life — relationships, finances, emotions, and health. Step 1 asks us to see the full picture honestly.', q: '"The admission that we were out of control turned out to be the bedrock on which a new life could be built."', tags: ['Step 1', 'Unmanageability'] },
  { sub: 'Step 2 — Came to Believe', sum: 'Came to believe that a Power greater than ourselves could restore us to sanity. This step requires nothing more than an open mind and willingness.', q: '"The only thing we need to begin this step is the willingness to believe that our own best thinking is not enough."', tags: ['Step 2', 'Faith'] },
  { sub: 'Step 2 — Restored to Sanity', sum: 'Step 2 invites us to recognize the insanity of our pattern and believe that something greater can restore us to a sane way of living.', q: '"We had tried everything we knew. Step 2 asks us to try something we did not know — something greater than ourselves."', tags: ['Step 2', 'Sanity'] },
  { sub: 'Step 3 — Turning It Over', sum: 'Made a decision to turn our will and our lives over to the care of a Higher Power as we understood it. Step 3 is a decision — not a feeling.', q: '"Step 3 is not about feeling ready. It is about making a decision before we are ready, and the feeling follows."', tags: ['Step 3', 'Surrender'] },
  { sub: 'Step 3 — Self-Will vs. Higher Will', sum: 'Step 3 addresses our central problem: self-will run riot. When we try to control everything, life becomes unmanageable. Turning it over brings peace.', q: '"Self-centeredness was not a character flaw — it was a survival strategy. Step 3 offers us a better one."', tags: ['Step 3', 'Self-Will'] },
  { sub: 'Step 4 — The Resentment Inventory', sum: 'Step 4 begins with listing resentments — who we resent, why, and what our part was. This written inventory reveals patterns driving our behavior.', q: '"Resentment is a primary threat to lasting sobriety. Step 4 is how we drain the wound."', tags: ['Step 4', 'Resentment'] },
  { sub: 'Step 4 — The Fear Inventory', sum: 'The fear inventory in Step 4 identifies the fears that drive our actions. Listing and sharing them begins the process of releasing their grip on us.', q: '"Most of our destructive behavior was rooted in fear. Step 4 names it so we can finally face it."', tags: ['Step 4', 'Fear'] },
  { sub: 'Step 4 — Searching and Fearless', sum: 'A searching and fearless moral inventory means holding nothing back. Step 4 requires honest examination of resentments, fears, and harms caused.', q: '"A searching inventory is one we write as if no one will read it — and then share as if everyone should."', tags: ['Step 4', 'Inventory'] },
  { sub: 'Step 5 — Admitting the Exact Nature', sum: 'Admitted to a Higher Power, to ourselves, and to another human being the exact nature of our wrongs. Step 5 breaks through the isolation of shame.', q: '"Secrets keep us sick. Step 5 is the step where we stop being alone with who we really are."', tags: ['Step 5', 'Honesty'] },
  { sub: 'Step 5 — Sharing with Another', sum: 'Sharing our inventory with another person is one of the most transformative acts in recovery. Being truly known — and accepted anyway — is healing.', q: '"We spent years hiding who we really were. Step 5 is the first time many of us were fully seen and not rejected."', tags: ['Step 5', 'Sharing'] },
  { sub: 'Step 6 — Entirely Ready', sum: 'Were entirely ready to have a Higher Power remove all these defects of character. Step 6 is about willingness — even when we cling to familiar defects.', q: '"Step 6 does not require perfection — only honest willingness. We do not have to want to let go. We just have to be willing to want to."', tags: ['Step 6', 'Willingness'] },
  { sub: 'Step 6 — Letting Go of Defects', sum: 'Some character defects feel like old friends. Step 6 asks us to become willing to let them all go — even the ones that once protected or served us.', q: '"The defects that kept us safe in addiction are the same ones that block us in recovery."', tags: ['Step 6', 'Character Defects'] },
  { sub: 'Step 7 — Humbly Asked', sum: 'Humbly asked a Higher Power to remove our shortcomings. Step 7 is grounded in humility — seeing ourselves as we truly are and asking for help to change.', q: '"Humility is not thinking less of ourselves. It is being willing to be changed by something greater."', tags: ['Step 7', 'Humility'] },
  { sub: 'Step 7 — The Practice of Surrender', sum: 'Asking for our shortcomings to be removed so we can better serve others. A daily practice of surrender and trust in a power greater than ourselves.', q: '"We do not ask for perfection — only for the willingness to stop standing in our own way."', tags: ['Step 7', 'Prayer'] },
  { sub: 'Step 8 — Making the List', sum: 'Made a list of all persons we had harmed and became willing to make amends to them all. Step 8 is about willingness and honest preparation.', q: '"The list in Step 8 is not about guilt — it is about responsibility. We write it to become willing to repair what we broke."', tags: ['Step 8', 'Willingness'] },
  { sub: 'Step 8 — Willingness to Make Amends', sum: 'Step 8 asks us to become willing to face those we have harmed. Some names come easily; others require prayer and time. Willingness is the only requirement.', q: '"We cannot always make every amends immediately. Step 8 asks us to start by becoming willing."', tags: ['Step 8', 'Amends'] },
  { sub: 'Step 9 — Making Direct Amends', sum: 'Made direct amends to such people wherever possible, except when to do so would injure them or others. Step 9 requires courage, sensitivity, and guidance.', q: '"An amends is not about how we feel doing it. It is about cleaning up what we left behind."', tags: ['Step 9', 'Amends'] },
  { sub: 'Step 9 — The Promises', sum: 'Through working Step 9, something remarkable begins: new freedom, new happiness, peace, and the ability to help others who are still suffering.', q: '"The promises of recovery are not handed to us — they are revealed through the work of making things right."', tags: ['Step 9', 'Promises'] },
  { sub: 'Step 9 — Living Amends', sum: 'Some amends cannot be made in words alone. Living amends means consistently showing up as a changed person — day after day, choice after choice.', q: '"The best amends we can make is to become someone our past could not have imagined."', tags: ['Step 9', 'Living Amends'] },
  { sub: 'Step 10 — Continued Personal Inventory', sum: 'Continued to take personal inventory and when we were wrong promptly admitted it. Step 10 is the maintenance step that keeps recovery current and honest.', q: '"We watch for selfishness, dishonesty, resentment, and fear — not as punishment, but as maintenance."', tags: ['Step 10', 'Inventory'] },
  { sub: 'Step 10 — Spot-Check Inventory', sum: 'A spot-check inventory can be done anytime during the day. When disturbed, we pause and honestly ask what is really driving the feeling.', q: '"When something bothers us, the question is not what they did — it is what we are going to do about our part."', tags: ['Step 10', 'Daily Practice'] },
  { sub: 'Step 11 — Prayer and Meditation', sum: 'Sought through prayer and meditation to improve our conscious contact with a Higher Power, seeking guidance and the strength to follow it.', q: '"Prayer and meditation are not about changing a Higher Power\'s mind. They are about changing our own."', tags: ['Step 11', 'Prayer'] },
  { sub: 'Step 11 — Morning Routine', sum: 'Step 11 suggests starting the day in prayer and reflection — asking for direction, clarity, and freedom from self-will before the day begins.', q: '"Beginning the day in conscious contact sets the tone for everything that follows."', tags: ['Step 11', 'Morning Practice'] },
  { sub: 'Step 11 — Conscious Contact', sum: 'Step 11 deepens our relationship with a Higher Power through daily practice. It is less about getting answers and more about staying connected.', q: '"Conscious contact is not a feeling we achieve — it is a practice we maintain."', tags: ['Step 11', 'Conscious Contact'] },
  { sub: 'Step 12 — Carrying the Message', sum: 'Having had a spiritual awakening as the result of these steps, we carry this message to others and practice these principles in all our affairs.', q: '"Nothing protects our own sobriety like helping someone else find theirs."', tags: ['Step 12', 'Service'] },
  { sub: 'Step 12 — Spiritual Awakening', sum: 'Step 12 begins with the recognition that something has changed — a personality shift that makes recovery not just possible but livable.', q: '"The awakening is usually not a moment. It is the gradual realization that we have become someone different."', tags: ['Step 12', 'Awakening'] },
  { sub: 'Step 12 — Practice These Principles', sum: 'Step 12 challenges us to practice recovery principles not just in meetings, but in every area of life — at work, at home, and in every relationship.', q: '"The steps are not a meeting thing — they are a life thing. Step 12 asks us to live them everywhere."', tags: ['Step 12', 'Principles'] },
];

const BILL_CARDS = [
  { sub: 'Humility — Foundation of Growth', sum: 'Self-reliance can become our greatest obstacle. Humility opens the door to all other virtues and genuine spiritual growth.', q: '"Pain honestly faced is never wasted — it becomes the foundation of genuine wisdom and compassion."', tags: ['Humility', 'Growth'] },
  { sub: 'Willingness to Grow', sum: 'Willingness to grow is the essence of spiritual development. Difficulty is not punishment — it is often the very instrument of progress.', q: '"Growth requires that we become willing to be changed before we are ready — and trust that the change will be worth it."', tags: ['Willingness', 'Progress'] },
  { sub: 'The Language of the Heart', sum: 'Genuine recovery writing and wisdom is ultimately about love, connection, and the kind of honest communication that heals.', q: '"The most powerful thing one person in recovery can say to another is simply: I know. I have been there. And it gets better."', tags: ['Communication', 'Heart'] },
  { sub: 'Depression and Recovery', sum: 'Depression is not a sign that recovery has failed. Honesty about it — rather than hiding it — is itself an act of courage that helps others.', q: '"Being honest about our struggles does not undermine recovery. It is what recovery looks like in real life."', tags: ['Depression', 'Honesty'] },
  { sub: 'Gratitude as Foundation', sum: 'Gratitude is not a feeling we wait for — it is a practice we choose. It is the essential attitude for maintaining sobriety and growing spiritually.', q: '"No act of service, however small, leaves us unchanged. Gratitude and giving are inseparable in recovery."', tags: ['Gratitude', 'Service'] },
  { sub: 'Unity in Diversity', sum: 'The strength of any recovery community lies in its diversity. Every background, belief, and experience enriches the whole.', q: '"Recovery does not ask where you came from. It only asks whether you are willing to change."', tags: ['Unity', 'Diversity'] },
  { sub: 'The Role of Suffering', sum: 'Suffering has purpose — it strips away pretense and opens us to genuine change. It is not wasted when we bring it honestly into recovery.', q: '"The suffering we survived is exactly what qualifies us to help someone else through theirs."', tags: ['Suffering', 'Purpose'] },
  { sub: 'Spiritual Awakening', sum: 'Early recovery founders recognized that most spiritual awakenings are gradual — a slow, accumulating shift rather than a sudden flash of light.', q: '"Most awakenings do not arrive like lightning. They come like a tide — and we only notice how far it has moved when we look back at the shore."', tags: ['Awakening', 'Spirituality'] },
  { sub: 'Leadership in Service', sum: 'Genuine recovery leadership is not governance — it is service. Those who lead best do so by example, not by authority.', q: '"The best leaders in recovery are the ones who make everyone around them feel less alone."', tags: ['Leadership', 'Service'] },
  { sub: 'Emotional Sobriety', sum: 'Emotional sobriety is the next frontier beyond physical sobriety — learning to live with life on its own terms, without needing to change how we feel.', q: '"Emotional sobriety is the ongoing work of becoming free — not from difficulty, but from the tyranny of our reaction to it."', tags: ['Emotional Sobriety', 'Growth'] },
  { sub: 'Courage Under Fire', sum: 'Recovery asks us to keep going despite imperfection — to face criticism, doubt, and our own character defects without giving up.', q: '"We are not asked to be perfect. We are asked to be willing — and to keep showing up despite our imperfections."', tags: ['Courage', 'Imperfection'] },
  { sub: 'The Gift of Anonymity', sum: 'Anonymity protects both the individual and the community from the dangers of ego and public recognition at the expense of principle.', q: '"When we lead with our recovery rather than our name, we remind everyone that the message matters more than the messenger."', tags: ['Anonymity', 'Ego'] },
  { sub: 'Love and Tolerance', sum: 'Love and tolerance of others is the code by which we try to live. Recovery transforms us into people capable of genuine and patient love.', q: '"Recovery asks us to love people we would never have chosen — and in doing so, we become someone we never expected."', tags: ['Love', 'Tolerance'] },
  { sub: 'Self-Examination', sum: 'Relentless but compassionate self-examination is the path to freedom. Honest self-appraisal is not about shame — it is about clarity.', q: '"Self-examination is not a punishment. It is how we stay honest with ourselves and useful to others."', tags: ['Self-Examination', 'Honesty'] },
  { sub: 'Fear and Faith', sum: 'Fear is the root of most problems in recovery. Faith — in something greater than our own thinking — is its most reliable antidote.', q: '"Where fear contracts, faith expands. The practice of recovery is learning to choose faith — especially when fear is louder."', tags: ['Fear', 'Faith'] },
  { sub: 'Service Above Self', sum: 'A life of service is the surest path to lasting recovery. Giving to others without expectation of return is the most protective act we know.', q: '"Service is not a chore in recovery — it is the thing that most reliably keeps us well."', tags: ['Service', 'Giving'] },
  { sub: 'Patience with Progress', sum: 'We claim spiritual progress rather than spiritual perfection. Growth is a lifelong journey, not a destination we arrive at.', q: '"Progress, not perfection — this is not just a slogan. It is the most honest description of what recovery actually looks like."', tags: ['Patience', 'Progress'] },
  { sub: 'Dealing with Resentment', sum: 'Resentment is among the greatest threats to lasting sobriety. Learning to pray for those we resent — however reluctantly — has freed countless people.', q: '"Praying for someone we resent does not mean we forgive them immediately. It means we stop letting them control our peace."', tags: ['Resentment', 'Prayer'] },
  { sub: 'The Fellowship\'s Future', sum: 'A strong recovery community is built on shared principles, not on personalities. Traditions ensure the fellowship survives long after any individual.', q: '"Any fellowship built on principles rather than personalities can outlast its founders. That was always the plan."', tags: ['Future', 'Traditions'] },
  { sub: 'Living with Imperfection', sum: 'Honesty about our own flaws is not a liability — it is one of the most powerful things we can offer someone who is still suffering.', q: '"The program does not work for perfect people. It works for imperfect people who are willing to keep trying."', tags: ['Imperfection', 'Willingness'] },
  { sub: 'A Partnership That Changed Everything', sum: 'The earliest twelve-step recovery began between two people who discovered that one struggling person talking honestly with another could keep both of them sober.', q: '"Two people who could not stay sober alone figured out that together, they could. That is the entire foundation."', tags: ['Partnership', 'Fellowship'] },
  { sub: 'Spiritual Roots of the Steps', sum: 'The twelve steps drew on spiritual principles already understood by many traditions: honesty, unselfishness, and love. They gave those principles a practical framework.', q: '"The steps did not invent these principles. They gave us a structure to actually live them — one day at a time."', tags: ['Spirituality', 'History'] },
  { sub: 'Emotional Sobriety — The Next Frontier', sum: 'Emotional sobriety means freedom from the tyranny of our own feelings and the demands we place on life and other people.', q: '"When we stop needing everything to be different than it is, we find that most of what we needed was already there."', tags: ['Emotional Sobriety', 'Maturity'] },
  { sub: 'The Traditions — A Living Legacy', sum: 'The twelve traditions protect the recovery community from the forces that would otherwise tear it apart — ego, money, prestige, and controversy.', q: '"Without shared principles to hold us together, any community will fracture. The traditions are the structure that keeps recovery intact."', tags: ['Traditions', 'Unity'] },
  { sub: 'Anonymity and Humility', sum: 'Declining public recognition to protect the principle of anonymity is an act of humility that benefits the whole community.', q: '"Anonymity reminds us that no individual is more important than the principles — and no recovery more important than the next person\'s."', tags: ['Anonymity', 'Humility'] },
  { sub: 'The Three Legacies of Recovery', sum: 'Recovery, unity, and service — these three legacies together form the complete foundation of twelve-step life. Each depends on the others.', q: '"Service keeps the doors open so that recovery stays possible for the next person who needs it."', tags: ['Service', 'Legacy'] },
  { sub: 'Wrestling with Doubt', sum: 'Even those with long-term sobriety wrestle with doubt, depression, and uncertainty. Sharing those struggles honestly is itself an act of recovery.', q: '"Doubt does not mean recovery has failed. It means we are still honest enough to admit we do not have all the answers."', tags: ['Doubt', 'Vulnerability'] },
  { sub: 'Spirituality vs. Religion', sum: 'Twelve-step recovery is a spiritual program, not a religious one. People of every faith — and none — have found a home in it.', q: '"The only requirement is willingness. Recovery has no monopoly on spirituality — it only has an approach that has worked for millions."', tags: ['Spirituality', 'Inclusivity'] },
  { sub: 'A Vision for Unity', sum: 'The vision for any lasting recovery community is one so deeply rooted in spiritual principles that no personality, crisis, or controversy can destroy it.', q: '"Unity is not uniformity. A recovery community is strongest when its members are free to be different — and still committed to the same principles."', tags: ['Unity', 'Vision'] },
  { sub: 'Surrender as Gateway', sum: 'Surrender is not defeat — it is the gateway to a new life. The paradox at the heart of recovery is that we find freedom by letting go.', q: '"Surrender is the only battle we win by stopping. Everything else in recovery flows from that one act."', tags: ['Surrender', 'Paradox'] },
];

// Recovery Vocabulary — original definitions and key recovery terms
const VOCAB_CARDS = [
  { sub: 'Allergy of the Body', sum: 'Addiction involves a physical component — once the first drink is taken, a craving is triggered that makes stopping nearly impossible through willpower alone.', q: '"Understanding why willpower fails is the first step toward finding what actually works."', tags: ['Medical', 'Allergy'], dq: ['How does understanding addiction as a physical condition change how you view yourself?', 'Why is it important that the craving starts only after the first drink?', 'How would you explain this concept to someone new to recovery?'] },
  { sub: 'Obsession of the Mind', sum: 'The mental obsession convinces a person they can drink safely despite all evidence to the contrary. It precedes the first drink and overrides rational thinking.', q: '"The problem is not the drink itself — it is the thought that one drink will be fine this time."', tags: ['Mental', 'Obsession'], dq: ['Can you recall a time the mental obsession convinced you it was safe to drink?', 'What tools help you interrupt that thought before it becomes action?', 'How does talking to someone else help break the mental obsession?'] },
  { sub: 'Phenomenon of Craving', sum: 'Once the first drink is taken, a physical craving kicks in — an overwhelming need for more. This distinguishes addiction from ordinary habit or social drinking.', q: '"One drink sets off something in us that ordinary people simply do not experience."', tags: ['Craving', 'Physical'], dq: ['How does the craving after the first drink differ from simply wanting a drink?', 'Why does willpower alone fail to stop it once it begins?', 'How does this concept help explain why moderation does not work for addicts?'] },
  { sub: 'Spiritual Malady', sum: 'Beneath the addiction lies a deeper condition — restlessness, irritability, and discontent that no substance ever truly relieved for long.', q: '"We were not drinking because life was bad. We were drinking because we felt empty, and we had found nothing yet to fill that emptiness."', tags: ['Spiritual', 'Malady'], dq: ['How do you experience restlessness, irritability, or discontent in your own life?', 'Why is treating the inner condition essential — not just stopping drinking?', 'Which steps have helped most with that underlying emptiness?'] },
  { sub: 'Psychic Change', sum: 'A profound inner change — a shift in perspective and values — is what makes lasting recovery possible. It cannot be produced by willpower alone.', q: '"We did not change by deciding to. We changed by surrendering to a process larger than our own willpower."', tags: ['Psychic Change', 'Transformation'], dq: ['What does a profound personality change look like in your recovery?', 'Was your change sudden or gradual, and how did you recognize it?', 'Why is inner transformation — not just sobriety — necessary for lasting change?'] },
  { sub: 'Cunning, Baffling, Powerful', sum: 'Addiction is cunning in how it deceives, baffling in how we repeat the same mistakes, and powerful in the grip it maintains long after we think we are safe.', q: '"The most dangerous moment is when we start to believe we have it completely figured out."', tags: ['Addiction', 'Warning'], dq: ['In what ways has addiction been cunning in your experience?', 'What makes it baffling — why do we repeat the same mistakes?', 'How do you stay vigilant even after years of sobriety?'] },
  { sub: 'Half Measures', sum: 'A halfhearted or partial effort at recovery leaves us vulnerable. Full commitment to the process is what produces lasting and genuine change.', q: '"We cannot give half of ourselves to recovery and expect to get a whole life back."', tags: ['Commitment', 'Action'], dq: ['Where in your recovery have you tried half measures, and what happened?', 'What does full commitment to the process look like in daily practice?', 'Why do half measures consistently fall short?'] },
  { sub: 'Moral Inventory', sum: 'A searching and fearless moral inventory — written, honest, and thorough — reveals the patterns that drove our addiction and caused harm to others.', q: '"Writing it down makes it permanent. We cannot revise it when it becomes uncomfortable."', tags: ['Inventory', 'Step 4'], dq: ['What patterns did your moral inventory reveal about your behavior?', 'Why must the inventory be both searching and fearless?', 'How did writing it down differ from just thinking about your past?'] },
  { sub: 'Character Defects', sum: 'Character defects are deeply ingrained patterns — selfishness, dishonesty, fear, resentment — that cause harm and block growth. Steps 6 and 7 address them directly.', q: '"The traits that once protected us in addiction become the very things that keep us stuck in recovery."', tags: ['Defects', 'Character'], dq: ['Which character defect has been the hardest for you to release?', 'How do selfishness, dishonesty, fear, and resentment show up in your life today?', 'What does being entirely ready for change actually feel like?'] },
  { sub: 'Shortcomings', sum: 'Shortcomings are the ways we fall short of the people we could be. Step 7 invites us to humbly ask a Higher Power to remove them — not by force of will, but by grace.', q: '"We are not asked to fix ourselves — only to be willing to be changed."', tags: ['Shortcomings', 'Humility'], dq: ['How do you distinguish between a shortcoming and a character defect?', 'Why does this step emphasize humility in asking for change?', 'In what ways do you still fall short of the person you want to be?'] },
  { sub: 'Amends', sum: 'Amends go beyond apology — they involve honestly acknowledging harm done, taking responsibility, and making restitution wherever possible through Steps 8 and 9.', q: '"An amends is a commitment to change, not just a request for forgiveness."', tags: ['Amends', 'Restitution'], dq: ['What is the difference between making amends and simply saying sorry?', 'How do you decide when making amends might cause more harm than good?', 'What has the amends process taught you about taking real responsibility?'] },
  { sub: 'Living Amends', sum: 'When direct contact would cause more harm, or when words alone are not enough, a living amends is the daily demonstration of genuine change through consistent behavior.', q: '"The living amends is the one that cannot be taken back — it is the changed life, lived day after day."', tags: ['Living Amends', 'Behavior'], dq: ['When is a living amends more appropriate than a direct one?', 'How do you demonstrate change through action rather than words?', 'What living amends are you actively making right now?'] },
  { sub: 'Rigorous Honesty', sum: 'Rigorous honesty goes beyond not lying — it means being truthful about our motives, fears, and actions, especially with ourselves. It is the foundation of recovery.', q: '"Recovery begins the moment we stop deceiving ourselves — that is the only honesty that actually matters."', tags: ['Honesty', 'Foundation'], dq: ['How does rigorous honesty differ from simply not telling lies?', 'Where do you struggle most with being honest with yourself?', 'Why is honesty described as the foundation of recovery?'] },
  { sub: 'Self-Will Run Riot', sum: 'Self-will run riot — the compulsive need to control people, places, and things — is at the root of most problems in addiction and early recovery.', q: '"Self-centeredness is not a personality quirk. For us, it was a survival strategy that stopped working."', tags: ['Self-Will', 'Control'], dq: ['Where does your self-will still try to control outcomes?', 'How is self-will the opposite of surrender?', 'What happens in your life when self-centeredness takes over?'] },
  { sub: 'Turning It Over', sum: 'Turning it over means releasing our grip on a problem, decision, or outcome and trusting a Higher Power with it. It is the practical heart of Step 3.', q: '"We cannot hold on with both hands and ask for help at the same time. We have to let go first."', tags: ['Surrender', 'Step 3'], dq: ['What does turning it over look like in your daily practice?', 'What is hardest for you to release to a Higher Power?', 'How has turning something over changed the outcome for you?'] },
  { sub: 'The Promises of Recovery', sum: 'Working the steps brings real rewards — new freedom, happiness, peace, and the ability to help others — that people in early recovery can barely imagine are possible.', q: '"The gifts of sobriety are not handed to us before the work — they are revealed through it."', tags: ['Promises', 'Hope'], dq: ['Which recovery promises have come true most clearly in your life?', 'How did doing the work lead to new freedom or happiness?', 'Which promise are you still waiting to fully experience?'] },
  { sub: 'Spiritual Awakening', sum: 'A spiritual awakening is a shift in perspective and personality — often gradual — that makes lasting recovery possible. It is usually recognized in hindsight.', q: '"Most of us did not notice our spiritual awakening happening. We only recognized it by looking back at who we used to be."', tags: ['Awakening', 'Step 12'], dq: ['Was your spiritual awakening sudden or gradual?', 'What new way of thinking or living has it brought?', 'How do you recognize a spiritual awakening in someone else?'] },
  { sub: 'Higher Power', sum: 'A Higher Power is whatever force greater than ourselves we choose to rely on. Recovery requires no specific belief — only willingness to accept help beyond our own thinking.', q: '"The only requirement for a Higher Power is that it be greater than the problem we cannot solve alone."', tags: ['Higher Power', 'Open-Minded'], dq: ['How has your understanding of a Higher Power evolved in recovery?', 'Why is willingness more important than a specific belief?', 'How do you rely on your Higher Power in everyday situations?'] },
  { sub: 'As We Understood', sum: 'This phrase ensures inclusivity — each person defines their own understanding of a Higher Power. Recovery has no religious requirement, only a spiritual suggestion.', q: '"The God of your understanding is personal. No one else gets to define it for you."', tags: ['Higher Power', 'Inclusivity'], dq: ['Why is this phrase so important to the accessibility of recovery?', 'How has your own understanding of a Higher Power evolved over time?', 'How does this language make the program available to people of all beliefs?'] },
  { sub: 'The Turning Point', sum: 'The turning point is the moment we stop fighting and start surrendering — when we finally become willing to accept help we could not accept before.', q: '"The turning point is not where we gave up. It is where we finally gave in to something that could actually help."', tags: ['Decision', 'Surrender'], dq: ['Can you describe your own turning point moment?', 'What does the shift from fighting to surrendering feel like?', 'Why is this described as a decision rather than a feeling?'] },
  { sub: 'Hitting Bottom', sum: 'For many, recovery began only after reaching a point of complete breakdown — physical, emotional, and spiritual — that finally made denial impossible to maintain.', q: '"The bottom is the place where the only direction left is up, and we finally become willing to move."', tags: ['Bottom', 'Despair'], dq: ['What did hitting bottom mean for you personally?', 'Why does the severity of the bottom vary so much from person to person?', 'How did your lowest point eventually become the beginning of your recovery?'] },
  { sub: 'The Mental Blank Spot', sum: 'The mental blank spot is the moment when an addicted person forgets all consequences and reaches for the first drink anyway — the obsession overriding reason.', q: '"In that moment, every good reason to stay sober simply vanished — and that is what made it so terrifying."', tags: ['Mental', 'Defense'], dq: ['Have you experienced the mental blank spot — the moment all consequences disappeared?', 'Why does knowledge of consequences alone fail to stop addiction?', 'What spiritual or practical defense do you use against it today?'] },
  { sub: 'Conscious Contact', sum: 'Conscious contact is an active, aware relationship with a Higher Power — maintained through daily prayer, meditation, and intentional openness.', q: '"Conscious contact is not a feeling we wait for. It is a practice we show up to, whether we feel it or not."', tags: ['Prayer', 'Meditation'], dq: ['What does conscious contact with a Higher Power feel like for you?', 'How do prayer and meditation differ in deepening that relationship?', 'What daily practice helps you maintain it?'] },
  { sub: 'Carrying the Message', sum: 'Carrying the message means sharing our experience, strength, and hope — not advice or opinions — with people who are still suffering from addiction.', q: '"We carry the message best not by telling people what to do, but by showing them who we have become."', tags: ['Service', 'Step 12'], dq: ['How do you carry the message in your daily life?', 'Why is sharing experience and hope more effective than giving advice?', 'What is the difference between carrying the message and carrying the person?'] },
  { sub: 'Restless, Irritable, Discontented', sum: 'Being sober but spiritually untreated means still carrying the restlessness, irritability, and discontent that drove the addiction — just without the temporary relief.', q: '"Sobriety without inner work just means being uncomfortable without relief. That is why doing the work matters."', tags: ['Dry Recovery', 'Spiritual'], dq: ['Have you experienced being physically sober but emotionally miserable?', 'What is the difference between sobriety and actual recovery?', 'What do you do when these feelings start creeping back in?'] },
  { sub: 'Repeating the Same Mistake', sum: 'The pattern of returning to drinking despite knowing the consequences illustrates that addiction is not a failure of willpower — it is a deeper condition requiring a deeper solution.', q: '"Knowing exactly what will happen and doing it anyway — that is what tells us we are dealing with more than ordinary habit."', tags: ['Insanity', 'Pattern'], dq: ['How does this pattern describe your own experience with addiction?', 'Why does knowledge of consequences not stop the behavior?', 'What finally broke through when willpower kept failing?'] },
  { sub: 'Two Types of Awakening', sum: 'Spiritual awakenings can be sudden and dramatic or quiet and gradual. Both are equally real. Most people in recovery experience the slow, accumulating kind.', q: '"Not all awakenings arrive like lightning. Most come like a slow sunrise — barely noticed until the world is already bright."', tags: ['Awakening', 'Types'], dq: ['Do you relate more to a sudden spiritual experience or the gradual kind?', 'Why is it important to know that both are equally valid?', 'How has your own spiritual awakening developed over time?'] },
  { sub: 'Daily Reprieve', sum: 'Recovery is not a permanent cure but a daily reprieve that depends on actively maintaining our spiritual condition. Each day requires renewed intention and action.', q: '"Recovery is not something we achieve and then own. It is something we maintain — one day at a time, every day."', tags: ['Daily', 'Maintenance'], dq: ['What does the daily reprieve mean for how you approach each morning?', 'How do you maintain your spiritual condition on a daily basis?', 'Why is recovery described as a reprieve rather than a permanent cure?'] },
  { sub: 'Reaching Out to Others', sum: 'Reaching out to someone still suffering is one of the most powerful tools in recovery — for both the person asking for help and the one offering it.', q: '"The phone call we make to help someone else often does more for our own sobriety than anything we do for ourselves."', tags: ['Service', 'Twelfth Step'], dq: ['How does reaching out to help someone else strengthen your own recovery?', 'What has been your experience trying to help someone still struggling?', 'Why does service to others provide such reliable protection from relapse?'] },
  { sub: 'Keep It Simple', sum: 'The program works best when we stop overcomplicating it — work the steps, attend meetings, be honest, help others, and trust the process one day at a time.', q: '"When we overthink recovery, we are usually trying to find a loophole. Keep it simple and do the work."', tags: ['Slogans', 'Simplicity'], dq: ['Where in your recovery do you tend to overcomplicate things?', 'How does keeping it simple help you stay focused on what matters?', 'What does trusting the process look like for you day to day?'] },
];

// Topic-specific content pools
const POOLS = {
  'big-book': {
    kp: ['Honesty is the foundation of all recovery', 'Half measures avail us nothing', 'The steps are a suggested program of recovery', 'Addiction involves a physical component and a mental obsession', 'A spiritual experience can come suddenly or gradually', 'One person in recovery talking to another is a cornerstone of healing', 'We must be willing to go to any lengths', 'Self-reliance fails where faith in something greater succeeds', 'Resentment is a primary threat to lasting sobriety', 'The gifts of recovery come through working the steps', 'Addiction is cunning, baffling, and powerful', 'Nothing protects sobriety like helping others find it'],
    dq: ['What section of this reading speaks to you most?', 'How has re-reading this material revealed new insights?', 'What idea changed your understanding of addiction?', 'How do you use these principles in your daily life?', 'Which story in the reading do you identify with most?', 'How has this reading helped you help others?', 'What passage would you share with someone new to recovery?'],
    rd: ['Recovery reading — this section', 'Step study — related step', 'Daily reflection — matching entry', 'Sponsor discussion — related topic', 'Meeting share — related experience', 'Journal entry — personal application'],
    ai: ['Read this section again this week with fresh eyes', 'Share a key idea from this reading at a meeting', 'Discuss this section with your sponsor', 'Highlight three ideas that speak to you', 'Read this section with someone new to the program'],
  },
  'reflections': {
    kp: ['Gratitude transforms our perspective', 'Acceptance does not mean approval', 'The present moment is all we truly have', 'Letting go is an act of faith', 'Self-pity is a luxury we cannot afford', 'Forgiveness sets us free', 'Every day is a fresh start', 'Surrender opens the door to a new way of living', 'Patience with ourselves is essential', 'We grow through discomfort', 'Connection breaks isolation', 'Joy is possible in sobriety'],
    dq: ['How does this reflection apply to your life today?', 'What daily practice helps you with this?', 'How has your perspective on this changed in recovery?', 'What tools do you use when struggling with this?', 'Can you share a specific experience with this?', 'How do you practice this principle daily?', 'What would you tell a newcomer about this?'],
    rd: ['Daily reflection — today\'s entry', 'Recovery reading — related chapter', 'Step study — related step', 'Meeting topic — related discussion', 'Journal entry — personal reflection', 'Sponsor conversation — related principle'],
    ai: ['Meditate on this reflection for 10 minutes', 'Write about this topic in your journal', 'Share on this topic at your next meeting', 'Practice this principle in one interaction today', 'Discuss this reflection with your sponsor'],
  },
  'step-talk': {
    kp: ['Each step builds on the one before it', 'The steps are suggested — but millions have found them essential', 'Working the steps with a sponsor deepens understanding', 'The steps address the root causes of addiction', 'Honesty, open-mindedness, and willingness are the keys', 'The steps are a design for living', 'We practice the steps, not perfect them', 'Spiritual growth comes through working all twelve steps', 'The maintenance steps (10, 11, 12) keep recovery alive', 'Each step requires action, not just thought', 'The steps transform our relationship with ourselves and others', 'We can always go deeper into any step'],
    dq: ['How did you first work this step?', 'What did this step reveal about yourself?', 'How has your understanding of this step deepened over time?', 'What was the hardest part of this step?', 'How do you practice this step today?', 'What would you tell a sponsee about this step?', 'How has this step changed your life?'],
    rd: ['Step study — this step in detail', 'Recovery reading — related chapter', 'Meeting topic — step discussion', 'Sponsor session — working this step', 'Journal entry — this step in your life', 'Service work — applying this step'],
    ai: ['Work on this step with your sponsor this week', 'Write about your experience with this step', 'Share on this step at a step meeting', 'Study this step through your own reading', 'Identify how this step applies to a current situation'],
  },
  'bill-sees-it': {
    kp: ['Recovery founders practiced what they preached — imperfectly but persistently', 'Humility opens the door to all other virtues', 'Emotional sobriety is the next frontier of recovery', 'Service to others is the foundation of lasting sobriety', 'Difficulty is often the touchstone of spiritual progress', 'Love and tolerance of others is the code we live by', 'We claim spiritual progress rather than spiritual perfection', 'Anonymity protects the fellowship from ego', 'Shared principles ensure the fellowship\'s survival', 'Honesty about our flaws inspires others', 'Unity in diversity strengthens the community', 'Courage means acting despite fear'],
    dq: ['How does this perspective apply to your life today?', 'What can you learn from the honest sharing of struggles in recovery?', 'How does this passage challenge you?', 'How has the wisdom of recovery shaped your understanding?', 'What would recovery wisdom say about your current situation?', 'How does this experience mirror your own?', 'What principle from this passage can you practice today?'],
    rd: ['Recovery wisdom — this passage', 'Step study — related tradition or step', 'Meeting share — applying this principle', 'Sponsor discussion — this concept', 'Journal entry — personal application', 'Service work — living this principle'],
    ai: ['Reflect on how this wisdom applies to you today', 'Share this principle at a meeting this week', 'Discuss this perspective with your sponsor', 'Write about what this passage means to your recovery', 'Identify one way to apply this principle today'],
  },
  'bb-vocab': {
    kp: ['Recovery uses precise language for a reason', 'Understanding terms deepens our program work', 'Recovery terms often have meanings beyond everyday usage', 'The medical and psychological roots of addiction inform the steps', 'Early recovery pioneers chose their words carefully', 'Vocabulary knowledge helps us carry the message clearly', 'Each term connects to a deeper spiritual principle', 'Newcomers benefit greatly from understanding recovery language', 'The steps themselves define many core recovery concepts', 'Recovery has its own language of hope and healing', 'Our understanding of these terms deepens over time', 'Clear language bridges the gap between suffering and solution'],
    dq: ['Which recovery term was most confusing when you first came in?', 'How has understanding a specific term changed your recovery?', 'What term would you explain differently to a newcomer?', 'How do you define this term from your own experience?', 'What recovery phrase carries the most personal meaning for you?', 'How has the language of recovery become part of your daily life?', 'What term do you think is most misunderstood?'],
    rd: ['Recovery reading — the relevant section', 'Step study — related step or concept', 'Meeting topic — vocabulary discussion', 'Sponsor conversation — understanding this term', 'Journal entry — personal definition', 'Service work — explaining this to a newcomer'],
    ai: ['Look up how this concept is described in your recovery reading', 'Explain this concept to a newcomer in your own words', 'Discuss this term with your sponsor or home group', 'Write a personal definition based on your experience', 'Share how this term applies to your life at a meeting'],
  },
};

function pick(arr, n) {
  const shuffled = [...arr].sort(() => Math.random() - 0.5);
  return shuffled.slice(0, n);
}

const LABEL_MAP = {
  'big-book': 'Recovery Reading',
  'reflections': 'Reflections',
  'step-talk': 'Step Talk',
  'bill-sees-it': 'Wisdom',
  'bb-vocab': 'Recovery Vocab',
  'random': 'Random',
};

function buildCard(base, topicId) {
  const label = LABEL_MAP[topicId] || topicId;
  const pool = POOLS[topicId] || POOLS['big-book'];
  return {
    cardSubtitle: `${label} — ${base.sub}`,
    summary: base.sum,
    quote: base.q,
    keyPoints: pick(pool.kp, 6),
    readings: pick(pool.rd, 3),
    actionItems: pick(pool.ai, 3),
    discussionQuestions: Array.isArray(base.dq) ? base.dq : pick(pool.dq, 5),
    tags: [...(base.tags || []), label],
  };
}

// Shuffle-bag: cycles through all cards in random order before repeating
const shuffleBags = {};

function getFromBag(topicId, pool) {
  if (!shuffleBags[topicId] || shuffleBags[topicId].length === 0) {
    // Fisher-Yates shuffle for true randomness
    const indices = Array.from({ length: pool.length }, (_, i) => i);
    for (let i = indices.length - 1; i > 0; i--) {
      const j = Math.floor(Math.random() * (i + 1));
      [indices[i], indices[j]] = [indices[j], indices[i]];
    }
    shuffleBags[topicId] = indices;
  }
  return shuffleBags[topicId].pop();
}

function getPoolForTopic(topicId) {
  switch (topicId) {
    case 'big-book': return BB_CARDS;
    case 'reflections': return REFL_CARDS;
    case 'step-talk': return STEP_CARDS;
    case 'bill-sees-it': return BILL_CARDS;
    case 'bb-vocab': return VOCAB_CARDS;
    case 'random': return [...BB_CARDS, ...REFL_CARDS, ...STEP_CARDS, ...BILL_CARDS, ...VOCAB_CARDS];
    default: return BB_CARDS;
  }
}

export function getPoolSize(topicId) {
  return getPoolForTopic(topicId).length;
}

export function getRandomCard(topicId) {
  const pool = getPoolForTopic(topicId);
  const idx = getFromBag(topicId, pool);
  const base = pool[idx];

  let effectiveId = topicId;
  if (topicId === 'random') {
    const bbLen = BB_CARDS.length;
    const refLen = REFL_CARDS.length;
    const stLen = STEP_CARDS.length;
    const billLen = BILL_CARDS.length;
    if (idx < bbLen) effectiveId = 'big-book';
    else if (idx < bbLen + refLen) effectiveId = 'reflections';
    else if (idx < bbLen + refLen + stLen) effectiveId = 'step-talk';
    else if (idx < bbLen + refLen + stLen + billLen) effectiveId = 'bill-sees-it';
    else effectiveId = 'bb-vocab';
  }
  return buildCard(base, effectiveId);
}
