// Generates card variants for each topic. Each topic has 50+ unique cards.
// Cards are built from template arrays and combined programmatically.

const BB_CARDS = [
  { sub: 'Chapter 1 — Bill\'s Story', sum: 'Bill W. shares his journey from hopeless alcoholic to co-founder of AA, illustrating the progression of alcoholism and the spiritual awakening that changed everything.', q: '"I was to know happiness, peace, and usefulness, in a way of life that is incredibly more wonderful as time passes." — p. 8', tags: ['Chapter 1', 'Bill W.'] },
  { sub: 'Chapter 2 — There Is a Solution', sum: 'The solution lies in a spiritual experience. This chapter explains what alcoholism really is and why only a profound change in consciousness can relieve it.', q: '"The great fact is just this, and nothing less: That we have had deep and effective spiritual experiences." — p. 25', tags: ['Chapter 2', 'Solution'] },
  { sub: 'Chapter 3 — More About Alcoholism', sum: 'This chapter demolishes the idea that true alcoholics can ever drink normally again. It presents compelling examples of the mental obsession that precedes every relapse.', q: '"The idea that somehow, someday he will control and enjoy his drinking is the great obsession of every abnormal drinker." — p. 30', tags: ['Chapter 3', 'Obsession'] },
  { sub: 'Chapter 4 — We Agnostics', sum: 'This chapter addresses those who struggle with the concept of God, suggesting an open mind and willingness to believe in a power greater than ourselves.', q: '"We found that as soon as we were able to lay aside prejudice and express even a willingness to believe, we commenced to get results." — p. 46', tags: ['Chapter 4', 'Higher Power'] },
  { sub: 'Chapter 5 — How It Works', sum: 'Rarely have we seen a person fail who has thoroughly followed our path. This chapter lays out the twelve steps and emphasizes rigorous honesty.', q: '"Remember that we deal with alcohol — cunning, baffling, powerful! Without help it is too much for us." — p. 58', tags: ['Chapter 5', 'Steps'] },
  { sub: 'Chapter 6 — Into Action', sum: 'Steps 5–9 in practical detail. Action, not just understanding, produces results. Faith without works is dead.', q: '"Faith without works is dead." — p. 76', tags: ['Chapter 6', 'Action'] },
  { sub: 'Chapter 7 — Working With Others', sum: 'Nothing ensures immunity from drinking like intensive work with other alcoholics. This chapter teaches twelfth-step work.', q: '"Our very lives, as ex-problem drinkers, depend upon our constant thought of others." — p. 20', tags: ['Chapter 7', 'Service'] },
  { sub: 'Chapter 8 — To Wives', sum: 'Acknowledges the suffering alcoholism inflicts on loved ones and offers guidance for patience, understanding, and family recovery.', q: '"Try not to condemn your alcoholic husband no matter what he says or does." — p. 108', tags: ['Chapter 8', 'Family'] },
  { sub: 'Chapter 9 — The Family Afterward', sum: 'Recovery brings changes the whole family must adjust to. Rebuilding trust and family life requires patience from everyone.', q: '"We think each family which has been relieved owes something to those who have not." — p. 132', tags: ['Chapter 9', 'Family'] },
  { sub: 'Chapter 10 — To Employers', sum: 'Alcoholism is a disease, not a moral failing. A recovered alcoholic may become an employer\'s most valuable person.', q: '"An alcoholic who has recovered is the most valuable person in many ways."', tags: ['Chapter 10', 'Work'] },
  { sub: 'Chapter 11 — A Vision for You', sum: 'The final chapter paints a hopeful picture of what life can be like in recovery and the fellowship that awaits.', q: '"Abandon yourself to God as you understand God. Admit your faults. Clear away the wreckage of your past." — p. 164', tags: ['Chapter 11', 'Hope'] },
  { sub: 'The Doctor\'s Opinion', sum: 'Dr. Silkworth explains alcoholism as a physical allergy combined with a mental obsession. A psychic change is necessary for recovery.', q: '"We believe the action of alcohol on chronic alcoholics is a manifestation of an allergy." — p. xxviii', tags: ['Doctor\'s Opinion', 'Disease'] },
  { sub: 'The Promises — Pages 83–84', sum: 'The Promises describe gifts that come from working the first nine steps: freedom, happiness, peace, and usefulness.', q: '"We are going to know a new freedom and a new happiness." — p. 83', tags: ['Promises', 'Hope'] },
  { sub: 'Acceptance — Page 417', sum: 'Dr. Paul O.\'s discovery that acceptance is the answer to all his problems resonates with millions in recovery.', q: '"And acceptance is the answer to all my problems today." — p. 417', tags: ['Acceptance', 'Page 417'] },
  { sub: 'Freedom from Bondage — Page 544', sum: 'Praying for those we resent sets us free. This story shows how prayer transforms resentment into compassion.', q: '"If you have a resentment you want to be free of, pray for the person or thing that you resent." — p. 552', tags: ['Resentment', 'Freedom'] },
  { sub: 'Third Step Prayer', sum: 'A surrendering of self-will to God. This prayer marks the turning point from self-reliance to trust in a higher power.', q: '"God, I offer myself to Thee — to build with me and to do with me as Thou wilt." — p. 63', tags: ['Step 3', 'Prayer'] },
  { sub: 'Seventh Step Prayer', sum: 'Asking God to remove our shortcomings so we can better serve others. A humble request for transformation.', q: '"My Creator, I am now willing that you should have all of me, good and bad." — p. 76', tags: ['Step 7', 'Prayer'] },
  { sub: 'Resentment Inventory — Pages 64–67', sum: 'The Big Book\'s method for examining resentments is the core of Step 4. Listing who, why, and our part brings freedom.', q: '"Resentment is the number one offender. It destroys more alcoholics than anything else." — p. 64', tags: ['Step 4', 'Resentment'] },
  { sub: 'Fear Inventory — Pages 67–68', sum: 'By identifying and sharing our fears, we begin to trust that a higher power will handle what we cannot.', q: '"We ask Him to remove our fear and direct our attention to what He would have us be." — p. 68', tags: ['Step 4', 'Fear'] },
  { sub: 'Daily Reprieve — Page 85', sum: 'Our sobriety depends on maintaining our spiritual condition each day. We are not cured — we live in a daily state of grace.', q: '"What we really have is a daily reprieve contingent on the maintenance of our spiritual condition." — p. 85', tags: ['Daily Reprieve', 'Maintenance'] },
  { sub: 'Emotional Sobriety', sum: 'Beyond physical sobriety lies emotional sobriety — handling life\'s ups and downs without being overwhelmed.', q: '"If we are painstaking about this phase of our development, we will be amazed before we are half way through." — p. 83', tags: ['Emotional Sobriety', 'Growth'] },
  { sub: 'Principles Before Personalities', sum: 'Tradition 12 reminds us to place principles above personalities. The message matters more than the messenger.', q: '"Anonymity is the spiritual foundation of all our Traditions." — Tradition 12', tags: ['Tradition 12', 'Principles'] },
  { sub: 'Personal Stories — Identification', sum: 'Shared experience is the bedrock of AA. Every story has a common thread — hope. The details differ but the feelings are the same.', q: '"Our stories disclose in a general way what we used to be like, what happened, and what we are like now." — p. 58', tags: ['Stories', 'Identification'] },
  { sub: 'Sex Inventory — Pages 68–70', sum: 'Examining where our behavior has been selfish, dishonest, or harmful in relationships. About honesty, not shame.', q: '"We subjected each relation to this test — was it selfish or not?" — p. 69', tags: ['Step 4', 'Relationships'] },
  { sub: 'Step 4 — Searching Moral Inventory', sum: 'A thorough and honest look at ourselves. Writing reveals patterns of behavior that have caused harm.', q: '"Made a searching and fearless moral inventory of ourselves." — Step 4', tags: ['Step 4', 'Inventory'] },
  { sub: 'Steps 8 & 9 — Making Amends', sum: 'We list those we\'ve harmed and become willing to make amends. Direct amends wherever possible, except when to do so would injure them or others.', q: '"The spiritual life is not a theory. We have to live it." — p. 83', tags: ['Steps 8-9', 'Amends'] },
  { sub: 'Step 10 — Continued Inventory', sum: 'The maintenance step. By continuing to take personal inventory and promptly admitting when we\'re wrong, we keep our side of the street clean.', q: '"Continue to watch for selfishness, dishonesty, resentment, and fear." — p. 84', tags: ['Step 10', 'Maintenance'] },
  { sub: 'Step 11 — Prayer & Meditation', sum: 'Deepening conscious contact with God through prayer and meditation. The spiritual practice that sustains long-term recovery.', q: '"Sought through prayer and meditation to improve our conscious contact with God." — Step 11', tags: ['Step 11', 'Meditation'] },
  { sub: 'Step 12 — Carrying the Message', sum: 'Having had a spiritual awakening, we carry the message and practice these principles in all our affairs.', q: '"We have a daily reprieve contingent on the maintenance of our spiritual condition." — p. 85', tags: ['Step 12', 'Service'] },
  { sub: 'Powerlessness Over People', sum: 'Step 1 extends beyond alcohol. We are powerless over people, places, and things. Accepting this brings peace.', q: '"Acceptance is the answer to all my problems today." — p. 417', tags: ['Step 1', 'Powerlessness'] },
];

const REFL_CARDS = [
  { sub: 'New Beginnings', sum: 'Each new day brings opportunity to renew our commitment to recovery, reflecting on growth and setting intentions grounded in the program.', q: '"I am going to know a new freedom and a new happiness." — Promises', tags: ['New Beginnings', 'Gratitude'] },
  { sub: 'Letting Go of Control', sum: 'Our need to control creates suffering. Letting go is trusting that a power greater than ourselves is in charge.', q: '"Let go and let God." — AA slogan', tags: ['Control', 'Surrender'] },
  { sub: 'Living in the Present', sum: 'Anxiety comes from the future; depression from the past. Recovery teaches us to live in the only moment we have — now.', q: '"One day at a time." — AA slogan', tags: ['Present Moment', 'Mindfulness'] },
  { sub: 'Dealing with Anger', sum: 'Anger is natural but can be deadly for alcoholics. Learning to process it without acting out is essential to sobriety.', q: '"If we were to live, we had to be free of anger." — p. 66', tags: ['Anger', 'Emotions'] },
  { sub: 'Gratitude Practice', sum: 'Gratitude is the antidote to self-pity, resentment, and fear. A daily gratitude practice transforms our outlook.', q: '"A grateful heart will never drink." — AA saying', tags: ['Gratitude', 'Practice'] },
  { sub: 'Self-Pity & Its Cure', sum: 'Self-pity isolates us and can lead back to drinking. The cure is action — getting outside ourselves through service.', q: '"Self-pity is one of the most unhappy and consuming defects." — As Bill Sees It, p. 238', tags: ['Self-Pity', 'Service'] },
  { sub: 'The Serenity Prayer in Action', sum: 'Learning to distinguish what we can and cannot change is the practical heart of recovery.', q: '"God, grant me the serenity to accept the things I cannot change..."', tags: ['Serenity Prayer', 'Acceptance'] },
  { sub: 'Loneliness in Recovery', sum: 'Loneliness is common but the program offers fellowship as the remedy. We are never alone unless we choose to be.', q: '"We are not a glum lot." — p. 132', tags: ['Loneliness', 'Fellowship'] },
  { sub: 'Expectations vs. Reality', sum: 'Unmet expectations are premeditated resentments. Releasing expectations opens us to how things actually are.', q: '"Expectations are premeditated resentments." — AA saying', tags: ['Expectations', 'Acceptance'] },
  { sub: 'Trust the Process', sum: 'Recovery is not a straight line. Trusting the process means believing the program works even when we can\'t see it.', q: '"It works if you work it." — AA saying', tags: ['Trust', 'Faith'] },
  { sub: 'Patience in Recovery', sum: 'We want everything now, but growth takes time. Patience with ourselves and others is a spiritual practice.', q: '"More will be revealed." — Big Book', tags: ['Patience', 'Growth'] },
  { sub: 'Honesty with Self', sum: 'Self-deception kept us sick. Honest self-appraisal is the foundation of all spiritual progress in recovery.', q: '"To thine own self be true." — AA medallion', tags: ['Honesty', 'Self-Awareness'] },
  { sub: 'Forgiveness', sum: 'Forgiving others — and ourselves — frees us from the prison of resentment. It does not mean condoning harm.', q: '"Holding a resentment is like drinking poison and expecting the other person to die."', tags: ['Forgiveness', 'Resentment'] },
  { sub: 'Service as Medicine', sum: 'When we are of service to others, our own problems shrink. Service is the rent we pay for our place in recovery.', q: '"Service is the rent we pay for living." — AA saying', tags: ['Service', 'Action'] },
  { sub: 'Courage to Change', sum: 'Change requires courage — the courage to face our fears, admit our wrongs, and step into the unknown.', q: '"Courage to change the things I can." — Serenity Prayer', tags: ['Courage', 'Change'] },
  { sub: 'Finding Your Higher Power', sum: 'A higher power can be anything greater than ourselves. The journey to find one is deeply personal and ongoing.', q: '"We found that as soon as we were able to lay aside prejudice and express willingness to believe, we commenced to get results." — p. 46', tags: ['Higher Power', 'Faith'] },
  { sub: 'Humility vs. Pride', sum: 'Pride keeps us stuck; humility opens doors. True humility is seeing ourselves as we really are — no more, no less.', q: '"Humility is not thinking less of yourself, but thinking of yourself less." — attributed', tags: ['Humility', 'Pride'] },
  { sub: 'Dealing with Loss', sum: 'Loss is part of life. In recovery, we learn to grieve without drinking and find strength in our fellowship and faith.', q: '"We will not regret the past nor wish to shut the door on it." — Promises', tags: ['Loss', 'Grief'] },
  { sub: 'Relationships in Recovery', sum: 'Recovery transforms our relationships. We learn to be honest, vulnerable, and present with the people we love.', q: '"We will intuitively know how to handle situations which used to baffle us." — Promises', tags: ['Relationships', 'Growth'] },
  { sub: 'Fear of the Future', sum: 'Fear of what might happen robs us of today. The program teaches us to trust that we will be given what we need.', q: '"Fear knocked at the door. Faith answered. No one was there."', tags: ['Fear', 'Faith'] },
  { sub: 'The Gift of Desperation', sum: 'Desperation brought us to recovery. What felt like our lowest point was actually the beginning of our transformation.', q: '"We perceive that only through utter defeat are we able to take our first steps." — 12 & 12', tags: ['Desperation', 'Hope'] },
  { sub: 'Practicing Kindness', sum: 'Simple acts of kindness connect us to others and remind us that recovery is about more than just not drinking.', q: '"Love and tolerance of others is our code." — Big Book, p. 84', tags: ['Kindness', 'Love'] },
  { sub: 'Spiritual Growth', sum: 'Spiritual growth is not about religion — it is about becoming more honest, open, and willing. It happens gradually.', q: '"We claim spiritual progress rather than spiritual perfection." — Big Book, p. 60', tags: ['Spirituality', 'Progress'] },
  { sub: 'Dealing with Criticism', sum: 'Criticism can trigger our defenses. In recovery, we learn to listen, consider, and respond rather than react.', q: '"Nothing pays off like restraint of tongue and pen." — 12 & 12', tags: ['Criticism', 'Restraint'] },
  { sub: 'Joy in Sobriety', sum: 'Recovery is not just about avoiding pain — it is about discovering genuine joy, laughter, and connection.', q: '"We are not a glum lot. If newcomers could see no joy in our existence, they wouldn\'t want it." — p. 132', tags: ['Joy', 'Happiness'] },
  { sub: 'When Life Gets Hard', sum: 'Difficult times test our recovery but also strengthen it. The tools of the program work in every situation.', q: '"This too shall pass." — AA saying', tags: ['Adversity', 'Resilience'] },
  { sub: 'Surrendering Outcomes', sum: 'We do the footwork and leave the results to God. Surrendering outcomes frees us from anxiety and control.', q: '"We do the footwork; God does the rest."', tags: ['Surrender', 'Outcomes'] },
  { sub: 'The Power of Meetings', sum: 'Meetings are where we share, listen, and connect. They remind us we are not alone and keep our recovery alive.', q: '"Meeting makers make it." — AA saying', tags: ['Meetings', 'Fellowship'] },
  { sub: 'Living Amends', sum: 'Some amends cannot be made in words. Living amends means consistently showing up as a changed person.', q: '"The spiritual life is not a theory. We have to live it." — p. 83', tags: ['Amends', 'Change'] },
  { sub: 'Wisdom of the Slogans', sum: 'AA slogans distill deep truths into simple phrases: Easy Does It, First Things First, Live and Let Live.', q: '"Easy does it — but do it." — AA saying', tags: ['Slogans', 'Wisdom'] },
];

// Step Talk — ONLY about the 12 Steps of AA
const STEP_CARDS = [
  { sub: 'Step 1 — Powerlessness', sum: 'We admitted we were powerless over alcohol — that our lives had become unmanageable. This is the foundation upon which all other steps rest.', q: '"We perceive that only through utter defeat are we able to take our first steps toward liberation and strength." — 12 & 12', tags: ['Step 1', 'Powerlessness'] },
  { sub: 'Step 1 — Unmanageability', sum: 'Unmanageability shows up in every area of life — relationships, finances, emotions, and health. Step 1 asks us to see the full picture.', q: '"Our admissions of personal powerlessness finally turn out to be firm bedrock upon which happy and purposeful lives may be built." — 12 & 12', tags: ['Step 1', 'Unmanageability'] },
  { sub: 'Step 2 — Came to Believe', sum: 'Came to believe that a Power greater than ourselves could restore us to sanity. This step requires nothing more than an open mind.', q: '"The only thing we need to commence spiritual growth is an open mind." — paraphrased, 12 & 12', tags: ['Step 2', 'Faith'] },
  { sub: 'Step 2 — Restored to Sanity', sum: 'Step 2 defines insanity as repeating the same behavior expecting different results. Believing in a power greater than ourselves begins the restoration.', q: '"We needed to ask ourselves but one short question: Do I now believe, or am I even willing to believe, that there is a Power greater than myself?" — Big Book, p. 47', tags: ['Step 2', 'Sanity'] },
  { sub: 'Step 3 — Turning It Over', sum: 'Made a decision to turn our will and our lives over to the care of God as we understood Him. Step 3 is a decision — not a feeling.', q: '"God, I offer myself to Thee — to build with me and to do with me as Thou wilt." — Big Book, p. 63', tags: ['Step 3', 'Surrender'] },
  { sub: 'Step 3 — Self-Will vs. God\'s Will', sum: 'Step 3 addresses our central problem: self-will run riot. When we try to run the show, life becomes unmanageable. Turning it over brings peace.', q: '"Selfishness — self-centeredness! That, we think, is the root of our troubles." — Big Book, p. 62', tags: ['Step 3', 'Self-Will'] },
  { sub: 'Step 4 — The Resentment Inventory', sum: 'Step 4 begins with listing our resentments. Who do we resent? Why? And what was our part? This written inventory reveals the patterns driving our behavior.', q: '"Resentment is the number one offender. It destroys more alcoholics than anything else." — Big Book, p. 64', tags: ['Step 4', 'Resentment'] },
  { sub: 'Step 4 — The Fear Inventory', sum: 'The fear inventory in Step 4 identifies the fears that drive our actions. By listing them and sharing them, we begin to find freedom from their grip.', q: '"We ask Him to remove our fear and direct our attention to what He would have us be." — Big Book, p. 68', tags: ['Step 4', 'Fear'] },
  { sub: 'Step 4 — Searching & Fearless', sum: 'A searching and fearless moral inventory means holding nothing back. Step 4 requires us to look at ourselves honestly — resentments, fears, and harms.', q: '"Made a searching and fearless moral inventory of ourselves." — Step 4', tags: ['Step 4', 'Inventory'] },
  { sub: 'Step 5 — Admitting the Exact Nature', sum: 'Admitted to God, to ourselves, and to another human being the exact nature of our wrongs. Step 5 breaks through the isolation of shame.', q: '"We pocket our pride and go to it, illuminating every twist of character." — 12 & 12, p. 58', tags: ['Step 5', 'Honesty'] },
  { sub: 'Step 5 — Sharing with Another', sum: 'The act of sharing our inventory with another person is transformative. Secrets keep us sick. Step 5 brings the relief of being truly known.', q: '"More than most people, the alcoholic leads a double life." — 12 & 12', tags: ['Step 5', 'Sharing'] },
  { sub: 'Step 6 — Entirely Ready', sum: 'Were entirely ready to have God remove all these defects of character. Step 6 is about willingness — even when we cling to our favorite defects.', q: '"The best we can do, with all the honesty that we can summon, is to try to be ready." — 12 & 12, p. 69', tags: ['Step 6', 'Willingness'] },
  { sub: 'Step 6 — Letting Go of Defects', sum: 'Some character defects feel comfortable. Step 6 asks us to become willing to let them all go — even the ones that once served us.', q: '"This is the step that separates the men from the boys." — 12 & 12', tags: ['Step 6', 'Character Defects'] },
  { sub: 'Step 7 — Humbly Asked Him', sum: 'Humbly asked Him to remove our shortcomings. Step 7 is grounded in humility — seeing ourselves as we truly are and asking for help to change.', q: '"My Creator, I am now willing that you should have all of me, good and bad." — Big Book, p. 76', tags: ['Step 7', 'Humility'] },
  { sub: 'Step 7 — The Seventh Step Prayer', sum: 'The Seventh Step Prayer asks God to remove our shortcomings so we can better serve His purpose. It is a daily act of surrender and trust.', q: '"I pray that you now remove from me every single defect of character which stands in the way of my usefulness to you and my fellows." — Big Book, p. 76', tags: ['Step 7', 'Prayer'] },
  { sub: 'Step 8 — Making the List', sum: 'Made a list of all persons we had harmed and became willing to make amends to them all. Step 8 is about willingness and preparation.', q: '"To a willing person the handicap of mending is less than the handicap of carrying the injury." — paraphrased, 12 & 12', tags: ['Step 8', 'Willingness'] },
  { sub: 'Step 8 — Willingness to Make Amends', sum: 'Step 8 asks us to become willing to face those we have harmed. Some names come easily; others require prayer and time. Willingness is the key.', q: '"We should not hesitate to ask God to remove any obstacles we face in making amends."', tags: ['Step 8', 'Amends'] },
  { sub: 'Step 9 — Making Direct Amends', sum: 'Made direct amends to such people wherever possible, except when to do so would injure them or others. Step 9 requires courage and sensitivity.', q: '"The spiritual life is not a theory. We have to live it." — Big Book, p. 83', tags: ['Step 9', 'Amends'] },
  { sub: 'Step 9 — The Promises', sum: 'Through working Step 9, the promises begin to materialize: new freedom, new happiness, peace, and the ability to help others.', q: '"We are going to know a new freedom and a new happiness." — Big Book, p. 83', tags: ['Step 9', 'Promises'] },
  { sub: 'Step 9 — Living Amends', sum: 'Some amends cannot be made in words alone. Living amends means consistently showing up as a changed person — day after day.', q: '"We will not regret the past nor wish to shut the door on it." — Big Book, p. 83', tags: ['Step 9', 'Living Amends'] },
  { sub: 'Step 10 — Continued Personal Inventory', sum: 'Continued to take personal inventory and when we were wrong promptly admitted it. Step 10 is the maintenance step that keeps recovery current.', q: '"Continue to watch for selfishness, dishonesty, resentment, and fear." — Big Book, p. 84', tags: ['Step 10', 'Inventory'] },
  { sub: 'Step 10 — Spot-Check Inventory', sum: 'A spot-check inventory can be done anytime during the day. When we feel disturbed, we pause and ask what\'s really going on inside.', q: '"When these crop up, we ask God at once to remove them. We discuss them with someone immediately." — Big Book, p. 84', tags: ['Step 10', 'Daily Practice'] },
  { sub: 'Step 11 — Prayer and Meditation', sum: 'Sought through prayer and meditation to improve our conscious contact with God, praying only for knowledge of His will and the power to carry it out.', q: '"Be quick to see where religious people are right. Make use of what they offer." — Big Book, p. 87', tags: ['Step 11', 'Prayer'] },
  { sub: 'Step 11 — Morning Routine', sum: 'Step 11 suggests a morning routine: on awakening, we ask God to direct our thinking and keep it free from self-pity, dishonesty, and self-seeking.', q: '"On awakening let us think about the twenty-four hours ahead." — Big Book, p. 86', tags: ['Step 11', 'Morning Practice'] },
  { sub: 'Step 11 — Conscious Contact', sum: 'Step 11 deepens our relationship with a higher power through daily practice. Prayer is talking to God; meditation is listening.', q: '"We ask God for inspiration, an intuitive thought or a decision." — Big Book, p. 86', tags: ['Step 11', 'Conscious Contact'] },
  { sub: 'Step 12 — Carrying the Message', sum: 'Having had a spiritual awakening as the result of these steps, we try to carry this message to alcoholics and practice these principles in all our affairs.', q: '"We have a daily reprieve contingent on the maintenance of our spiritual condition." — Big Book, p. 85', tags: ['Step 12', 'Service'] },
  { sub: 'Step 12 — Spiritual Awakening', sum: 'Step 12 begins with the recognition of a spiritual awakening — a personality change sufficient to bring about recovery from alcoholism.', q: '"Having had a spiritual awakening as the result of these steps..." — Step 12', tags: ['Step 12', 'Awakening'] },
  { sub: 'Step 12 — Practice These Principles', sum: 'Step 12 challenges us to practice AA principles not just in meetings, but in all our affairs — at work, at home, and in every relationship.', q: '"Practical experience shows that nothing will so much insure immunity from drinking as intensive work with other alcoholics." — Big Book, p. 89', tags: ['Step 12', 'Principles'] },
];

const BILL_CARDS = [
  { sub: 'Humility — Foundation of Growth', sum: 'Self-reliance can become our greatest obstacle. Humility opens the door to all other virtues and genuine spiritual growth.', q: '"For us, the process of gaining a new perspective was unbelievably painful." — Bill W.', tags: ['Humility', 'Growth'] },
  { sub: 'Willingness to Grow', sum: 'Bill believed that willingness to grow is the essence of spiritual development. Pain is often the touchstone of progress.', q: '"Pain is the touchstone of spiritual progress." — Bill W.', tags: ['Willingness', 'Progress'] },
  { sub: 'The Language of the Heart', sum: 'Bill\'s letters reveal a man who understood that recovery is ultimately about love, connection, and honest communication.', q: '"The language of the heart is the language of recovery." — Bill W.', tags: ['Communication', 'Heart'] },
  { sub: 'Depression and Recovery', sum: 'Bill W. himself suffered from depression. His honesty about it gave permission for others to acknowledge their own struggles.', q: '"I think the way we handle depression may be one of the most important things we do." — Bill W.', tags: ['Depression', 'Honesty'] },
  { sub: 'Gratitude as Foundation', sum: 'Bill saw gratitude as the essential attitude for maintaining sobriety and growing spiritually.', q: '"No satisfaction has been deeper and no joy greater than in a twelfth-step job well done." — Bill W.', tags: ['Gratitude', 'Service'] },
  { sub: 'Unity in Diversity', sum: 'Bill recognized that AA\'s strength lies in its diversity. Every background, belief, and experience enriches the fellowship.', q: '"Our membership ought to include all who suffer from alcoholism." — Bill W.', tags: ['Unity', 'Diversity'] },
  { sub: 'The Role of Suffering', sum: 'Bill believed that suffering has purpose — it strips away pretense and opens us to genuine change and connection.', q: '"Years ago I used to commiserate with all people who suffered. Now I commiserate only with those who suffer in ignorance." — Bill W.', tags: ['Suffering', 'Purpose'] },
  { sub: 'Spiritual Awakening', sum: 'Bill\'s own spiritual experience in the hospital was sudden and dramatic, but he came to understand that most awakenings are gradual.', q: '"Most of our experiences are the educational variety — they develop slowly over time." — Appendix II', tags: ['Awakening', 'Spirituality'] },
  { sub: 'Leadership in AA', sum: 'Bill insisted that AA have no leaders in the traditional sense. Trusted servants, not governors, guide the fellowship.', q: '"Our leaders are but trusted servants; they do not govern." — Tradition 2', tags: ['Leadership', 'Service'] },
  { sub: 'Emotional Sobriety', sum: 'In his famous letter, Bill described emotional sobriety as the next frontier — learning to handle life on life\'s terms.', q: '"I think that many oldsters who have put our AA \'determination\' to the test still find they lack emotional sobriety." — Bill W.', tags: ['Emotional Sobriety', 'Growth'] },
  { sub: 'Courage Under Fire', sum: 'Bill faced criticism, doubt, and his own character defects. His willingness to keep going despite imperfection inspires us.', q: '"We are not saints. The point is that we are willing to grow along spiritual lines." — p. 60', tags: ['Courage', 'Imperfection'] },
  { sub: 'The Gift of Anonymity', sum: 'Bill understood that anonymity protects both the individual and the fellowship from the dangers of ego and fame.', q: '"Anonymity is the greatest single protection the Fellowship has." — Bill W.', tags: ['Anonymity', 'Ego'] },
  { sub: 'Love and Tolerance', sum: 'Bill believed that love and tolerance of others is our code. Recovery transforms us into people capable of genuine love.', q: '"Love and tolerance of others is our code." — p. 84', tags: ['Love', 'Tolerance'] },
  { sub: 'Self-Examination', sum: 'Bill practiced relentless self-examination and encouraged others to do the same. Honest self-appraisal is the path to freedom.', q: '"Continued to take personal inventory and when we were wrong promptly admitted it." — Step 10', tags: ['Self-Examination', 'Honesty'] },
  { sub: 'Fear and Faith', sum: 'Bill saw fear as the root of most problems and faith as its antidote. We replace fear with trust in a higher power.', q: '"We ask Him to remove our fear and direct our attention to what He would have us be." — p. 68', tags: ['Fear', 'Faith'] },
  { sub: 'Service Above Self', sum: 'Bill modeled a life of service. He believed that giving to others is the surest way to receive the gifts of recovery.', q: '"Practical experience shows that nothing will so much insure immunity from drinking as intensive work with other alcoholics." — p. 89', tags: ['Service', 'Giving'] },
  { sub: 'Patience with Progress', sum: 'Bill reminded us that we claim spiritual progress rather than spiritual perfection. Growth is a lifelong journey.', q: '"We claim spiritual progress rather than spiritual perfection." — p. 60', tags: ['Patience', 'Progress'] },
  { sub: 'Dealing with Resentment', sum: 'Bill knew resentment as the number one offender. His teachings on prayer for those we resent have freed countless alcoholics.', q: '"Resentment is the number one offender." — p. 64', tags: ['Resentment', 'Prayer'] },
  { sub: 'The Fellowship\'s Future', sum: 'Bill envisioned AA as a lasting beacon of hope. His traditions ensure the fellowship survives long after any individual.', q: '"I am sure that no fellowship has taken more care about its future." — Bill W.', tags: ['Future', 'Traditions'] },
  { sub: 'Living with Imperfection', sum: 'Bill was honest about his own flaws. His imperfection reminds us that the program works for imperfect people.', q: '"We are not saints. The point is that we are willing to grow." — p. 60', tags: ['Imperfection', 'Willingness'] },
  { sub: 'Bill and Dr. Bob — A Partnership', sum: 'The friendship between Bill W. and Dr. Bob is the foundation of AA. Two hopeless alcoholics discovered that one talking to another could keep both sober.', q: '"The spark that was to flare into the first AA group was struck at Akron on June 10, 1935." — AA Comes of Age', tags: ['Dr. Bob', 'Fellowship'] },
  { sub: 'The Oxford Group Roots', sum: 'Bill credited the Oxford Group principles — honesty, unselfishness, purity, and love — as the spiritual seedbed from which the twelve steps grew.', q: '"The principles we borrowed from the Oxford Group were the four absolutes: honesty, purity, unselfishness, and love." — Bill W.', tags: ['Oxford Group', 'History'] },
  { sub: 'Bill\'s Letter on Emotional Sobriety', sum: 'In his 1958 Grapevine letter, Bill described emotional sobriety as the next frontier — freedom from the tyranny of our own feelings and demands on life.', q: '"If we examine every disturbance we have, great or small, we will find at the root of it some unhealthy dependency and its consequent unhealthy demand." — Bill W., 1958', tags: ['Emotional Sobriety', 'Maturity'] },
  { sub: 'The Twelve Traditions — Bill\'s Legacy', sum: 'Bill fought for the Traditions even when they were unpopular. He understood that without principles of unity, AA would destroy itself from within.', q: '"The Twelve Traditions are to the spirit of AA what the Twelve Steps are to the individual." — Bill W.', tags: ['Traditions', 'Unity'] },
  { sub: 'Bill and the Struggle with Fame', sum: 'Bill repeatedly turned down public honors to protect the principle of anonymity. He believed that fame could corrupt both individuals and the fellowship.', q: '"We must do what we can to discourage the natural human tendency toward power, fame, and personal gain." — Bill W.', tags: ['Fame', 'Anonymity'] },
  { sub: 'AA\'s Third Legacy — Service', sum: 'Bill defined AA\'s three legacies as Recovery (the Steps), Unity (the Traditions), and Service (the structure that keeps AA alive for future generations).', q: '"Our Twelfth Step — carrying the message — is the basic service that the AA Fellowship gives." — Bill W.', tags: ['Service', 'Third Legacy'] },
  { sub: 'Bill\'s Struggles with Doubt', sum: 'Even after years of sobriety, Bill wrestled with doubt, depression, and uncertainty. His willingness to share these struggles made the program more honest and accessible.', q: '"I saw that I had been living too much alone, too much in the past." — Bill W.', tags: ['Doubt', 'Vulnerability'] },
  { sub: 'Spirituality vs. Religion', sum: 'Bill insisted that AA is a spiritual, not a religious, program. He welcomed people of all faiths — and none — into the fellowship.', q: '"We have no monopoly on God; we merely have an approach that worked with us." — Bill W.', tags: ['Spirituality', 'Inclusivity'] },
  { sub: 'Bill\'s Vision for Unity', sum: 'Bill dreamed of an AA that would outlast its founders — a fellowship so deeply rooted in spiritual principles that no person, crisis, or controversy could destroy it.', q: '"The unity of Alcoholics Anonymous is the most cherished quality our society has." — Bill W.', tags: ['Unity', 'Vision'] },
  { sub: 'The Concept of Surrender', sum: 'Bill\'s own experience at Towns Hospital taught him that surrender is not defeat — it is the gateway to a new life. He spent decades helping others understand this paradox.', q: '"We admitted we were licked. We did it every time we made a decision which was solidly based on one of the Twelve Steps." — Bill W.', tags: ['Surrender', 'Paradox'] },
];

// Big Book Vocabulary — definitions and key terms from AA literature
const VOCAB_CARDS = [
  { sub: 'Allergy of the Body', sum: 'Dr. Silkworth described alcoholism as a physical allergy — once an alcoholic takes the first drink, a craving is triggered that makes stopping nearly impossible.', q: '"We believe… that the action of alcohol on these chronic alcoholics is a manifestation of an allergy." — The Doctor\'s Opinion, p. xxviii', tags: ['Medical', 'Allergy'], dq: ['How does understanding alcoholism as a physical allergy change the way you view your drinking?', 'Why is it important that the craving starts only after the first drink?', 'How would you explain the allergy concept to someone new to AA?'] },
  { sub: 'Obsession of the Mind', sum: 'The mental obsession is the irrational thought that convinces an alcoholic they can drink safely despite all evidence to the contrary. It precedes the first drink.', q: '"The main problem of the alcoholic centers in his mind, rather than in his body." — Big Book, p. 23', tags: ['Mental', 'Obsession'], dq: ['Can you recall a time the mental obsession convinced you it was safe to drink?', 'Why does the Big Book say the problem centers in the mind, not the body?', 'What tools help you combat the mental obsession today?'] },
  { sub: 'Phenomenon of Craving', sum: 'Once an alcoholic takes the first drink, a physical craving kicks in — an overwhelming need for more. This craving distinguishes the alcoholic from the normal drinker.', q: '"…he develops the phenomenon of craving." — The Doctor\'s Opinion, p. xxvi', tags: ['Craving', 'Physical'], dq: ['How does the craving after the first drink differ from simply wanting a drink?', 'Why can\'t willpower alone stop the craving once it begins?', 'How does this concept help you understand why moderation doesn\'t work for alcoholics?'] },
  { sub: 'Spiritual Malady', sum: 'The spiritual malady is the restlessness, irritability, and discontent that drives the alcoholic to drink. It is the underlying condition that the steps address.', q: '"…unless this person can experience an entire psychic change there is very little hope of his recovery." — The Doctor\'s Opinion, p. xxix', tags: ['Spiritual', 'Malady'], dq: ['How do you experience restlessness, irritability, or discontent in your own life?', 'Why is treating the spiritual malady essential — not just stopping drinking?', 'Which steps have helped you most with the underlying spiritual condition?'] },
  { sub: 'Psychic Change', sum: 'A psychic change — also called a spiritual experience or awakening — is the profound personality shift necessary for recovery. It transforms our thinking and way of living.', q: '"…there must be a profound personality change to overcome alcoholism." — The Doctor\'s Opinion', tags: ['Psychic Change', 'Transformation'], dq: ['What does a "profound personality change" look like in your recovery?', 'Was your psychic change sudden or gradual, and how did you recognize it?', 'Why is a personality shift — not just sobriety — necessary for lasting recovery?'] },
  { sub: 'Cunning, Baffling, Powerful', sum: 'This phrase describes alcohol\'s deceptive nature. It is cunning in how it tricks us, baffling in that we repeat the same mistakes, and powerful in its grip on us.', q: '"Remember that we deal with alcohol — cunning, baffling, powerful!" — Big Book, p. 58', tags: ['Alcohol', 'Warning'], dq: ['In what ways has alcohol been cunning in your experience?', 'What makes alcoholism baffling — why do we repeat the same mistakes?', 'How do you stay vigilant against something this powerful?'] },
  { sub: 'Half Measures', sum: 'Half measures refers to a halfhearted or partial attempt at the program. The Big Book warns that anything less than full commitment will not produce lasting recovery.', q: '"Half measures availed us nothing. We stood at the turning point." — Big Book, p. 59', tags: ['Commitment', 'Action'], dq: ['Where in your recovery have you tried half measures, and what happened?', 'What does full commitment to the program look like in daily practice?', 'Why does the Big Book say half measures "availed us nothing"?'] },
  { sub: 'Moral Inventory', sum: 'A moral inventory (Step 4) is an honest, written self-examination of our resentments, fears, and harms done. It reveals the patterns of thinking and behavior that fueled our drinking.', q: '"Made a searching and fearless moral inventory of ourselves." — Step 4', tags: ['Inventory', 'Step 4'], dq: ['What patterns did your moral inventory reveal about your behavior?', 'Why must the inventory be both searching and fearless?', 'How did writing it down differ from just thinking about your past?'] },
  { sub: 'Character Defects', sum: 'Character defects are the ingrained patterns of behavior — selfishness, dishonesty, fear, resentment — that cause harm to ourselves and others. Steps 6 and 7 address them.', q: '"Were entirely ready to have God remove all these defects of character." — Step 6', tags: ['Defects', 'Character'], dq: ['Which character defect has been the hardest for you to let go of?', 'How do selfishness, dishonesty, fear, and resentment show up in your life today?', 'What does being "entirely ready" to have defects removed really mean?'] },
  { sub: 'Shortcomings', sum: 'Shortcomings are closely related to character defects — they are the ways we fall short of the people we could be. Step 7 asks us to humbly request their removal.', q: '"Humbly asked Him to remove our shortcomings." — Step 7', tags: ['Shortcomings', 'Humility'], dq: ['How do you distinguish between a shortcoming and a character defect?', 'Why does Step 7 emphasize humility in asking for their removal?', 'In what ways do you still fall short of the person you want to be?'] },
  { sub: 'Amends', sum: 'Amends go beyond a simple apology — they involve acknowledging the harm done, taking responsibility, and making restitution where possible. Steps 8 and 9 guide the process.', q: '"Made direct amends to such people wherever possible, except when to do so would injure them or others." — Step 9', tags: ['Amends', 'Restitution'], dq: ['What is the difference between making amends and simply saying sorry?', 'How do you decide when making amends might injure someone?', 'What has the amends process taught you about taking responsibility?'] },
  { sub: 'Living Amends', sum: 'A living amends means changing our behavior permanently. When words are not enough or direct amends could cause harm, we show our change through consistent action.', q: '"We will not regret the past nor wish to shut the door on it." — Big Book, p. 83', tags: ['Living Amends', 'Behavior'], dq: ['When is a living amends more appropriate than a direct amends?', 'How do you show change through consistent action rather than words?', 'What living amends are you making in your life right now?'] },
  { sub: 'Rigorous Honesty', sum: 'Rigorous honesty goes beyond not lying — it means being truthful with ourselves about our motives, fears, and actions. It is the foundation upon which recovery is built.', q: '"…a manner of living which demands rigorous honesty." — Big Book, p. 58', tags: ['Honesty', 'Foundation'], dq: ['How does rigorous honesty differ from simply not telling lies?', 'Where do you struggle most with being honest with yourself?', 'Why is honesty described as the foundation of recovery?'] },
  { sub: 'Self-Will Run Riot', sum: 'Self-will run riot describes the alcoholic\'s compulsive need to control people, places, and things. It is the root of most problems and the opposite of surrender.', q: '"Selfishness — self-centeredness! That, we think, is the root of our troubles." — Big Book, p. 62', tags: ['Self-Will', 'Control'], dq: ['Where does your self-will still try to control outcomes?', 'How is self-will the opposite of surrender?', 'What happens in your life when self-centeredness takes over?'] },
  { sub: 'Turning It Over', sum: 'Turning it over means releasing our grip on a problem, decision, or outcome and trusting a Higher Power with it. It is the essence of Step 3.', q: '"God, I offer myself to Thee — to build with me and to do with me as Thou wilt." — Big Book, p. 63', tags: ['Surrender', 'Step 3'], dq: ['What does "turning it over" look like in your daily practice?', 'What is hardest for you to release and trust a Higher Power with?', 'How has turning something over changed the outcome for you?'] },
  { sub: 'The Promises', sum: 'The Promises are a set of assurances in the Big Book that describe the rewards of working the steps: new freedom, happiness, serenity, and the ability to help others.', q: '"We are going to know a new freedom and a new happiness." — Big Book, p. 83', tags: ['Promises', 'Hope'], dq: ['Which of the Promises has come true most clearly in your life?', 'How did working the steps lead to new freedom or happiness for you?', 'Which Promise are you still waiting to see materialize?'] },
  { sub: 'Spiritual Awakening', sum: 'A spiritual awakening is the personality change sufficient to bring about recovery. It may be sudden or gradual — what matters is a new way of thinking and living.', q: '"Having had a spiritual awakening as the result of these steps…" — Step 12', tags: ['Awakening', 'Step 12'], dq: ['Was your spiritual awakening sudden or gradual?', 'What new way of thinking or living has your awakening brought?', 'How do you recognize a spiritual awakening in someone else?'] },
  { sub: 'Higher Power', sum: 'A Higher Power is whatever force greater than ourselves we choose to rely on. AA requires no specific belief — only willingness to accept help from something beyond our own ego.', q: '"…a Power greater than ourselves could restore us to sanity." — Step 2', tags: ['Higher Power', 'Open-Minded'], dq: ['How has your understanding of a Higher Power changed since coming to AA?', 'Why is willingness more important than a specific belief?', 'How do you rely on your Higher Power in everyday situations?'] },
  { sub: 'God As We Understood Him', sum: 'This phrase ensures inclusivity — each person defines their own understanding of God or a Higher Power. AA has no religious requirements, only spiritual suggestions.', q: '"Made a decision to turn our will and our lives over to the care of God as we understood Him." — Step 3', tags: ['God', 'Inclusivity'], dq: ['Why is "as we understood Him" such an important phrase in AA?', 'How does this language make the program accessible to people of all beliefs?', 'How has your own understanding of God evolved in recovery?'] },
  { sub: 'The Turning Point', sum: 'The turning point is the moment of decision described in Step 3 — when we stop fighting and start surrendering. It marks the shift from self-will to willingness.', q: '"Half measures availed us nothing. We stood at the turning point." — Big Book, p. 59', tags: ['Decision', 'Surrender'], dq: ['Can you describe your own turning point moment?', 'What does the shift from fighting to surrendering feel like?', 'Why is the turning point described as a decision rather than a feeling?'] },
  { sub: 'Pitiful and Incomprehensible Demoralization', sum: 'This phrase describes the devastating bottom that many alcoholics reach — a state of complete physical, mental, and spiritual breakdown that defies rational explanation.', q: '"…pitiful and incomprehensible demoralization." — Big Book, p. 30', tags: ['Bottom', 'Despair'], dq: ['What does "incomprehensible demoralization" mean from your own experience?', 'Why is this state described as both pitiful and incomprehensible?', 'How did reaching this bottom eventually lead to your recovery?'] },
  { sub: 'Mental Blank Spot', sum: 'The mental blank spot is the mysterious moment when an alcoholic forgets all the consequences and reaches for a drink. It is the obsession overriding all rational thought.', q: '"The alcoholic at certain times has no effective mental defense against the first drink." — Big Book, p. 43', tags: ['Mental', 'Defense'], dq: ['Have you experienced the mental blank spot — forgetting all consequences before a drink?', 'Why does the Big Book say we have no effective mental defense?', 'What spiritual defense do you use against the mental blank spot today?'] },
  { sub: 'Conscious Contact', sum: 'Conscious contact refers to an active, aware relationship with a Higher Power through prayer and meditation. Step 11 is dedicated to deepening this connection.', q: '"Sought through prayer and meditation to improve our conscious contact with God…" — Step 11', tags: ['Prayer', 'Meditation'], dq: ['What does conscious contact with a Higher Power feel like for you?', 'How do prayer and meditation differ in deepening that connection?', 'What daily practice helps you maintain conscious contact?'] },
  { sub: 'Carrying the Message', sum: 'Carrying the message means sharing our experience, strength, and hope with other alcoholics. It is the primary purpose of every AA member and group.', q: '"Our primary purpose is to stay sober and help other alcoholics to achieve sobriety." — Preamble', tags: ['Service', 'Step 12'], dq: ['How do you carry the message in your daily life?', 'Why is sharing experience, strength, and hope more effective than giving advice?', 'What is the difference between carrying the message and carrying the alcoholic?'] },
  { sub: 'Restless, Irritable, and Discontented', sum: 'This phrase from the Doctor\'s Opinion describes the dry drunk — an alcoholic who is sober but spiritually untreated, still suffering from the underlying condition.', q: '"…they are restless, irritable and discontented, unless they can again experience the sense of ease and comfort which comes at once by taking a few drinks." — p. xxviii', tags: ['Dry Drunk', 'Spiritual'], dq: ['Have you experienced being sober but restless, irritable, and discontented?', 'What is the difference between being sober and being spiritually treated?', 'What do you do when you notice these feelings creeping in?'] },
  { sub: 'The Jaywalker', sum: 'The jaywalker analogy illustrates the insanity of alcoholism — repeatedly crossing against traffic despite being injured, unable to learn from consequences. It shows why willpower alone fails.', q: '"Our behavior is as absurd and incomprehensible with respect to the first drink as that of an individual with a passion, say, for jay-walking." — Big Book, p. 37', tags: ['Insanity', 'Analogy'], dq: ['How does the jaywalker analogy describe your own pattern with alcohol?', 'Why does knowing the consequences not stop an alcoholic from drinking?', 'What finally broke through when willpower alone kept failing?'] },
  { sub: 'Spiritual Experience vs. Spiritual Awakening', sum: 'Appendix II clarifies that most spiritual awakenings are gradual — the "educational variety" — rather than the sudden, dramatic type Bill W. had. Both are equally valid.', q: '"Most of our experiences are what the psychologist William James calls the \'educational variety\' because they develop slowly over a period of time." — Appendix II', tags: ['Awakening', 'Types'], dq: ['Do you relate more to a sudden spiritual experience or the gradual educational variety?', 'Why is it important to know that both types of awakening are equally valid?', 'How has your spiritual awakening developed over time?'] },
  { sub: 'Daily Reprieve', sum: 'Recovery is not a permanent cure but a daily reprieve contingent on the maintenance of our spiritual condition. Each day requires renewed commitment and action.', q: '"What we really have is a daily reprieve contingent on the maintenance of our spiritual condition." — Big Book, p. 85', tags: ['Daily', 'Maintenance'], dq: ['What does "daily reprieve" mean for how you approach each day?', 'How do you maintain your spiritual condition on a daily basis?', 'Why is recovery described as a reprieve rather than a cure?'] },
  { sub: 'Twelfth-Step Call', sum: 'A twelfth-step call is the act of reaching out to a suffering alcoholic to share your experience and offer help. It is one of the most powerful tools in recovery — for both parties.', q: '"Practical experience shows that nothing will so much insure immunity from drinking as intensive work with other alcoholics." — Big Book, p. 89', tags: ['Service', 'Twelfth Step'], dq: ['How does making a twelfth-step call help the person making it, not just the one receiving?', 'What has been your experience reaching out to a suffering alcoholic?', 'Why does the Big Book say working with others ensures immunity from drinking?'] },
  { sub: 'Keep It Simple', sum: 'Though not a direct Big Book quote, this slogan captures the program\'s essence — don\'t overthink, don\'t complicate. Work the steps, go to meetings, help others, trust the process.', q: '"Our book is meant to be suggestive only. We realize we know only a little." — Big Book, p. 164', tags: ['Slogans', 'Simplicity'], dq: ['Where in your recovery do you tend to overcomplicate things?', 'How does keeping it simple help you stay focused on what matters?', 'What does "trust the process" look like for you day to day?'] },
];

// Topic-specific content pools
const POOLS = {
  'big-book': {
    kp: ['Honesty is the foundation of all recovery', 'Half measures availed us nothing', 'The steps are suggested as a program of recovery', 'Alcoholism is a physical allergy plus a mental obsession', 'A spiritual experience can come suddenly or gradually', 'One alcoholic talking to another is the foundation of AA', 'We must be willing to go to any lengths', 'Self-reliance fails where faith succeeds', 'Resentment is the number one offender', 'The promises come true through working the steps', 'We deal with alcohol — cunning, baffling, powerful', 'Nothing ensures immunity like working with others'],
    dq: ['What chapter of the Big Book speaks to you most?', 'How has re-reading the Big Book revealed new insights?', 'What passage changed your understanding of alcoholism?', 'How do you use the Big Book in your daily life?', 'Which Big Book story do you identify with most?', 'How has the Big Book helped you help others?', 'What Big Book passage would you share with a newcomer?'],
    rd: ['Big Book — this chapter', '12 & 12 — related step', 'Daily Reflections — matching entry', 'Dr. Bob and the Good Oldtimers', 'AA Comes of Age — related section', 'Living Sober — related topic'],
    ai: ['Read this Big Book chapter this week', 'Share a Big Book passage at a meeting', 'Discuss this chapter with your sponsor', 'Highlight three passages that speak to you', 'Read this chapter aloud with a sponsee'],
  },
  'reflections': {
    kp: ['Gratitude transforms our perspective', 'Acceptance does not mean approval', 'The present moment is all we truly have', 'Letting go is an act of faith', 'Self-pity is a luxury we cannot afford', 'Forgiveness sets us free', 'Every day is a fresh start', 'Surrender opens the door to a new way of living', 'Patience with ourselves is essential', 'We grow through discomfort', 'Connection breaks isolation', 'Joy is possible in sobriety'],
    dq: ['How does this reflection apply to your life today?', 'What daily practice helps you with this?', 'How has your perspective on this changed in recovery?', 'What tools do you use when struggling with this?', 'Can you share a specific experience with this?', 'How do you practice this principle daily?', 'What would you tell a newcomer about this?'],
    rd: ['Daily Reflections — today\'s entry', 'Living Sober — related chapter', 'As Bill Sees It — matching passage', '12 & 12 — related step', 'Grapevine — related article', 'Came to Believe — related story'],
    ai: ['Meditate on this reflection for 10 minutes', 'Write about this topic in your journal', 'Share on this topic at your next meeting', 'Practice this principle in one interaction today', 'Discuss this reflection with your sponsor'],
  },
  'step-talk': {
    kp: ['Each step builds on the one before it', 'The steps are suggested — not required — but millions have found them essential', 'Working the steps with a sponsor deepens understanding', 'The steps address the root causes of alcoholism', 'Honesty, open-mindedness, and willingness are the keys', 'The steps are a design for living', 'We practice the steps, not perfect them', 'Spiritual growth comes through working all twelve steps', 'The maintenance steps (10, 11, 12) keep recovery alive', 'Each step requires action, not just thought', 'The steps transform our relationship with ourselves and others', 'We can always go deeper into any step'],
    dq: ['How did you first work this step?', 'What did this step reveal about yourself?', 'How has your understanding of this step deepened over time?', 'What was the hardest part of this step?', 'How do you practice this step today?', 'What would you tell a sponsee about this step?', 'How has this step changed your life?'],
    rd: ['12 & 12 — this step', 'Big Book — related chapter', 'A Guide to the Big Book\'s Design for Living', 'Daily Reflections — step-related entry', 'Drop the Rock — related chapter', 'Living Sober — related practice'],
    ai: ['Work on this step with your sponsor this week', 'Write about your experience with this step', 'Share on this step at a step meeting', 'Read the 12 & 12 chapter on this step', 'Identify how this step applies to a current situation'],
  },
  'bill-sees-it': {
    kp: ['Bill W. practiced what he preached — imperfectly but persistently', 'Humility opens the door to all other virtues', 'Emotional sobriety is the next frontier of recovery', 'Service to others is the foundation of lasting sobriety', 'Pain is the touchstone of spiritual progress', 'Love and tolerance of others is our code', 'We claim spiritual progress rather than spiritual perfection', 'Anonymity protects the fellowship from ego', 'The traditions ensure AA\'s survival', 'Bill\'s honesty about his flaws inspires us', 'Unity in diversity strengthens the fellowship', 'Courage means acting despite fear'],
    dq: ['How does Bill\'s perspective on this apply to your life?', 'What can you learn from Bill\'s honesty about his own struggles?', 'How does this passage from Bill challenge you?', 'How has Bill\'s writing shaped your understanding of recovery?', 'What would Bill say about your current situation?', 'How does Bill\'s experience mirror your own?', 'What principle from this passage can you practice today?'],
    rd: ['As Bill Sees It — this passage', 'AA Comes of Age — related chapter', 'Bill W.\'s letters — The Language of the Heart', '12 & 12 — related tradition or step', 'Grapevine — Bill W. articles', 'Pass It On — Bill\'s biography'],
    ai: ['Read this passage from As Bill Sees It', 'Reflect on how Bill\'s words apply to you today', 'Share a Bill W. quote at a meeting this week', 'Discuss Bill\'s perspective with your sponsor', 'Write about what this passage means to your recovery'],
  },
  'bb-vocab': {
    kp: ['The Big Book uses precise language for a reason', 'Understanding terms deepens our program work', 'Many AA terms have specific meanings beyond everyday usage', 'The Doctor\'s Opinion introduces key medical concepts', 'Bill and the early members chose their words carefully', 'Vocabulary knowledge helps us carry the message clearly', 'Each term connects to a deeper spiritual principle', 'Newcomers benefit greatly from understanding AA language', 'The steps themselves define many core recovery terms', 'Recovery has its own language of hope and healing', 'Definitions evolve as our understanding deepens', 'The Big Book\'s language bridges the gap between suffering and solution'],
    dq: ['Which Big Book term was most confusing when you first came in?', 'How has understanding a specific term changed your recovery?', 'What term would you explain differently to a newcomer?', 'How do you define this term from your own experience?', 'What Big Book phrase carries the most personal meaning for you?', 'How has the language of recovery become part of your daily life?', 'What term do you think is most misunderstood?'],
    rd: ['Big Book — The Doctor\'s Opinion', 'Big Book — Appendix II (Spiritual Experience)', 'Big Book — Chapter 5 (How It Works)', 'Living Sober — Key Concepts', '12 & 12 — Related Step or Tradition', 'AA Grapevine — Language of the Heart'],
    ai: ['Look up this term in the Big Book and note the page', 'Explain this concept to a newcomer in your own words', 'Discuss this term with your sponsor or home group', 'Write a personal definition based on your experience', 'Share how this term applies to your life at a meeting'],
  },
};

function pick(arr, n) {
  const shuffled = [...arr].sort(() => Math.random() - 0.5);
  return shuffled.slice(0, n);
}

const LABEL_MAP = {
  'big-book': 'Big Book',
  'reflections': 'Reflections',
  'step-talk': 'Step Talk',
  'bill-sees-it': 'Bill Sees It',
  'bb-vocab': 'BB Vocab',
  'random': 'Random',
};

function buildCard(base, topicId) {
  const label = LABEL_MAP[topicId] || topicId;
  const pool = POOLS[topicId] || POOLS['big-book'];
  return {
    cardSubtitle: `${label} — ${base.sub}`,
    summary: base.sum,
    quote: base.q,
    keyPoints: pick(pool.kp, 6),
    readings: pick(pool.rd, 3),
    actionItems: pick(pool.ai, 3),
    discussionQuestions: Array.isArray(base.dq) ? base.dq : pick(pool.dq, 5),
    tags: [...(base.tags || []), label],
  };
}

// Shuffle-bag: cycles through all cards in random order before repeating
const shuffleBags = {};

function getFromBag(topicId, pool) {
  if (!shuffleBags[topicId] || shuffleBags[topicId].length === 0) {
    // Fisher-Yates shuffle for true randomness
    const indices = Array.from({ length: pool.length }, (_, i) => i);
    for (let i = indices.length - 1; i > 0; i--) {
      const j = Math.floor(Math.random() * (i + 1));
      [indices[i], indices[j]] = [indices[j], indices[i]];
    }
    shuffleBags[topicId] = indices;
  }
  return shuffleBags[topicId].pop();
}

function getPoolForTopic(topicId) {
  switch (topicId) {
    case 'big-book': return BB_CARDS;
    case 'reflections': return REFL_CARDS;
    case 'step-talk': return STEP_CARDS;
    case 'bill-sees-it': return BILL_CARDS;
    case 'bb-vocab': return VOCAB_CARDS;
    case 'random': return [...BB_CARDS, ...REFL_CARDS, ...STEP_CARDS, ...BILL_CARDS, ...VOCAB_CARDS];
    default: return BB_CARDS;
  }
}

export function getPoolSize(topicId) {
  return getPoolForTopic(topicId).length;
}

export function getRandomCard(topicId) {
  const pool = getPoolForTopic(topicId);
  const idx = getFromBag(topicId, pool);
  const base = pool[idx];

  let effectiveId = topicId;
  if (topicId === 'random') {
    const bbLen = BB_CARDS.length;
    const refLen = REFL_CARDS.length;
    const stLen = STEP_CARDS.length;
    const billLen = BILL_CARDS.length;
    if (idx < bbLen) effectiveId = 'big-book';
    else if (idx < bbLen + refLen) effectiveId = 'reflections';
    else if (idx < bbLen + refLen + stLen) effectiveId = 'step-talk';
    else if (idx < bbLen + refLen + stLen + billLen) effectiveId = 'bill-sees-it';
    else effectiveId = 'bb-vocab';
  }
  return buildCard(base, effectiveId);
}
